<?php

namespace Database\Seeders;

use App\Enums\LogExportStatus;
use App\Enums\TimberCategory;
use App\Models\Species;
use Illuminate\Database\Seeder;

/**
 * The Cameroon timber species catalogue.
 *
 * Idempotent — `updateOrCreate` keyed on `slug`, safe to run in production.
 *
 * DATA NOTE. Botanical names, families, trade/local names, densities,
 * durability classes and typical uses are drawn from established timber
 * references. The REGULATORY fields are different:
 *
 *  - `log_export_status` is a PLACEHOLDER. It is seeded as `unknown` for every
 *    species. Cameroon's log-export schedules are set by MINFOF and the annual
 *    finance law and change with policy; nothing here may be presented as legal
 *    guidance until verified against the current MINFOF publications.
 *  - `commercial_category` is a COMMERCIAL / MARKET grouping, not a MINFOF tax
 *    category or felling class.
 *  - `is_promoted` reflects the general trade sense of an "essence de
 *    promotion" (a lesser-known species pushed to broaden the harvest), not a
 *    current official promotion list.
 *  - `is_cites_listed` is set only where the listing is well established
 *    (Pericopsis elata; and the CoP19 Appendix II listings of African Afzelia,
 *    Khaya, Pterocarpus and Guibourtia populations). Everything else is left
 *    false rather than guessed — notably Diospyros crassiflora, since the CITES
 *    Diospyros listing covers Madagascar populations, not Cameroon's.
 */
class SpeciesSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->catalogue() as $i => $row) {
            // Explicit defaults so a re-run also *clears* values that were removed
            // from the catalogue, instead of leaving stale data behind.
            $row = array_merge([
                'is_cites_listed' => false,
                'cites_appendix' => null,
                // Placeholder: never asserted as the legal position. See class docblock.
                'log_export_status' => LogExportStatus::Unknown->value,
                'janka_hardness' => null,
            ], $row);

            $row['sort_order'] = $i;
            $row['is_published'] = true;
            $row['meta_title'] ??= $this->metaTitle($row);
            $row['meta_description'] ??= $this->metaDescription($row);

            $slug = $row['slug'];
            unset($row['slug']);

            Species::updateOrCreate(['slug' => $slug], $row);
        }
    }

    /** @param array<string, mixed> $row */
    private function metaTitle(array $row): string
    {
        $sci = $row['scientific_name'] ? ' ('.$row['scientific_name'].')' : '';

        return str($row['common_name'].$sci.' — Cameroon Timber Species | Cameroon Timber Hub')->limit(255)->value();
    }

    /** @param array<string, mixed> $row */
    private function metaDescription(array $row): string
    {
        return Species::wordSafeExcerpt(strip_tags((string) $row['description']), Species::META_DESCRIPTION_LIMIT);
    }

    /**
     * Ordered by commercial prominence — `sort_order` follows this array.
     *
     * @return list<array<string, mixed>>
     */
    private function catalogue(): array
    {
        $primary = TimberCategory::PrimaryHardwood->value;
        $promoted = TimberCategory::PromotedSpecies->value;
        $secondary = TimberCategory::SecondaryHardwood->value;
        $softwood = TimberCategory::Softwood->value;
        $specialty = TimberCategory::Specialty->value;

        return [
            [
                'slug' => 'ayous',
                'common_name' => 'Ayous',
                'scientific_name' => 'Triplochiton scleroxylon',
                'family' => 'Malvaceae',
                'trade_names' => ['Obeche', 'Wawa', 'Abachi', 'Samba', 'African whitewood'],
                'local_names' => ['Ayous', 'Wawa'],
                'description' => 'Ayous, traded internationally as Obeche, is Cameroon\'s highest-volume export timber. The wood is pale cream to straw-yellow, lightweight and remarkably dimensionally stable once dried, with a fine even texture and slightly interlocked grain. It machines and glues easily, which makes it the default choice for mouldings, joinery blanks and plywood core stock. Its heartwood is not naturally durable, so it is used almost exclusively in interior and protected applications.',
                'characteristics' => ['Colour' => 'Pale cream to straw yellow', 'Grain' => 'Slightly interlocked', 'Texture' => 'Fine and even', 'Workability' => 'Excellent — machines, glues and finishes easily'],
                'density_kg_m3_min' => 320, 'density_kg_m3_max' => 450,
                'durability_class' => 'Class 5 (Not Durable)', 'janka_hardness' => 1900,
                'typical_uses' => ['Mouldings and joinery', 'Plywood core and blockboard', 'Furniture components', 'Model making', 'Packaging and light carpentry'],
                'commercial_category' => $primary, 'is_promoted' => false,
                'region_availability' => ['East', 'Centre', 'South', 'Littoral', 'South-West'],
            ],
            [
                'slug' => 'sapele',
                'common_name' => 'Sapele',
                'scientific_name' => 'Entandrophragma cylindricum',
                'family' => 'Meliaceae',
                'trade_names' => ['Sapelli', 'Sapele mahogany', 'Aboudikro'],
                'local_names' => ['Sapelli'],
                'description' => 'Sapele is a medium-density reddish-brown hardwood and one of Cameroon\'s flagship export species. Its interlocked grain produces the ribbon or pencil-stripe figure prized in quartersawn boards and sliced veneer, and the wood darkens attractively with age. It is stronger and denser than true mahogany while remaining workable, though the interlocked grain can tear on planing. Widely used for windows, doors, furniture and boat interiors.',
                'characteristics' => ['Colour' => 'Medium to dark reddish brown', 'Grain' => 'Interlocked, often ribbon-figured', 'Texture' => 'Fine and uniform', 'Odour' => 'Cedar-like when freshly cut'],
                'density_kg_m3_min' => 600, 'density_kg_m3_max' => 700,
                'durability_class' => 'Class 3 (Moderately Durable)', 'janka_hardness' => 5700,
                'typical_uses' => ['Windows and exterior joinery', 'Doors and staircases', 'Fine furniture and cabinetmaking', 'Decorative sliced veneer', 'Musical instruments'],
                'commercial_category' => $primary, 'is_promoted' => false,
                'region_availability' => ['East', 'South', 'Centre'],
            ],
            [
                'slug' => 'iroko',
                'common_name' => 'Iroko',
                'scientific_name' => 'Milicia excelsa',
                'family' => 'Moraceae',
                'trade_names' => ['Kambala', 'Odum', 'Mvule', 'African teak'],
                'local_names' => ['Abang', 'Mandji'],
                'description' => 'Iroko is a durable golden-brown hardwood widely used as a teak substitute. It is naturally very resistant to decay and insect attack without treatment, which makes it a mainstay for exterior joinery, decking, marine work and laboratory worktops. Freshly sawn timber is yellowish and weathers to a rich mid-brown. Occasional hard calcium deposits ("stone") in the log can blunt saw teeth.',
                'characteristics' => ['Colour' => 'Yellow-brown darkening to golden brown', 'Grain' => 'Interlocked', 'Texture' => 'Medium to coarse', 'Movement' => 'Small — very stable in service'],
                'density_kg_m3_min' => 620, 'density_kg_m3_max' => 700,
                'durability_class' => 'Class 1–2 (Very Durable)', 'janka_hardness' => 5600,
                'typical_uses' => ['Exterior joinery and cladding', 'Decking and garden furniture', 'Marine and boat building', 'Worktops and laboratory benches', 'Flooring'],
                'commercial_category' => $primary, 'is_promoted' => false,
                'region_availability' => ['East', 'Centre', 'South', 'Littoral', 'South-West'],
            ],
            [
                'slug' => 'sipo',
                'common_name' => 'Sipo',
                'scientific_name' => 'Entandrophragma utile',
                'family' => 'Meliaceae',
                'trade_names' => ['Utile', 'Assie', 'Sipo mahogany'],
                'local_names' => ['Sipo'],
                'description' => 'Sipo, traded as Utile, is a close relative of Sapele with a slightly coarser texture and a more uniform reddish-brown colour. The grain is interlocked but the stripe figure is broader and less pronounced than Sapele\'s. It is moderately durable, stable in service and machines well, making it a favourite for high-grade exterior joinery and panelled doors.',
                'characteristics' => ['Colour' => 'Uniform reddish brown', 'Grain' => 'Interlocked', 'Texture' => 'Medium to coarse', 'Movement' => 'Small'],
                'density_kg_m3_min' => 550, 'density_kg_m3_max' => 700,
                'durability_class' => 'Class 2–3 (Durable to Moderately Durable)', 'janka_hardness' => 5400,
                'typical_uses' => ['Exterior joinery and windows', 'Panelled doors', 'Furniture and cabinetwork', 'Sliced veneer', 'Boat building'],
                'commercial_category' => $primary, 'is_promoted' => false,
                'region_availability' => ['East', 'South', 'Centre'],
            ],
            [
                'slug' => 'kosipo',
                'common_name' => 'Kosipo',
                'scientific_name' => 'Entandrophragma candollei',
                'family' => 'Meliaceae',
                'trade_names' => ['Omu', 'Heavy sapele', 'Kosipo'],
                'local_names' => ['Kosipo'],
                'description' => 'Kosipo is the darkest and heaviest of the commercial Entandrophragma species, with a purplish to chocolate-brown heartwood. The grain is strongly interlocked and the texture coarser than Sapele, so surfaces need care in planing. It is used for furniture, joinery, flooring and decorative veneer where a deeper colour than Sapele is wanted.',
                'characteristics' => ['Colour' => 'Dark purple-brown to chocolate', 'Grain' => 'Strongly interlocked', 'Texture' => 'Coarse', 'Working' => 'Tears easily — reduce cutting angle'],
                'density_kg_m3_min' => 620, 'density_kg_m3_max' => 750,
                'durability_class' => 'Class 3 (Moderately Durable)', 'janka_hardness' => 4900,
                'typical_uses' => ['Furniture and cabinetwork', 'Interior joinery', 'Flooring', 'Decorative veneer'],
                'commercial_category' => $primary, 'is_promoted' => false,
                'region_availability' => ['East', 'South', 'Centre'],
            ],
            [
                'slug' => 'tiama',
                'common_name' => 'Tiama',
                'scientific_name' => 'Entandrophragma angolense',
                'family' => 'Meliaceae',
                'trade_names' => ['Edinam', 'Gedu Nohor', 'Tiama'],
                'local_names' => ['Tiama'],
                'description' => 'Tiama is the lightest of the commercial Entandrophragma group, with a pale to medium reddish-brown heartwood and a fairly open texture. It dries readily and works easily, though the interlocked grain calls for sharp tooling. It is used for interior joinery, furniture parts, plywood faces and general utility work.',
                'characteristics' => ['Colour' => 'Pale to medium reddish brown', 'Grain' => 'Interlocked', 'Texture' => 'Moderately coarse', 'Drying' => 'Dries fairly rapidly'],
                'density_kg_m3_min' => 480, 'density_kg_m3_max' => 620,
                'durability_class' => 'Class 3 (Moderately Durable)', 'janka_hardness' => 4000,
                'typical_uses' => ['Interior joinery', 'Furniture components', 'Plywood faces', 'Rotary and sliced veneer'],
                'commercial_category' => $primary, 'is_promoted' => false,
                'region_availability' => ['East', 'South', 'Centre'],
            ],
            [
                'slug' => 'tali',
                'common_name' => 'Tali',
                'scientific_name' => 'Erythrophleum ivorense',
                'family' => 'Fabaceae',
                'trade_names' => ['Missanda', 'Alui', 'Sasswood', 'Erun'],
                'local_names' => ['Elone', 'Tali'],
                'description' => 'Tali is a very dense, very durable orange- to reddish-brown hardwood used wherever timber must survive ground contact, water or heavy traffic. It resists decay, termites and marine borers, which makes it a standard choice for hydraulic works, bridges, sleepers and heavy-duty decking. The wood is hard on tools and pre-boring is required for nails and screws. Sawdust from the genus is irritant, so extraction and masks are recommended.',
                'characteristics' => ['Colour' => 'Orange-brown to dark red-brown', 'Grain' => 'Interlocked', 'Texture' => 'Medium to coarse', 'Handling' => 'Dust is irritant — use extraction'],
                'density_kg_m3_min' => 850, 'density_kg_m3_max' => 1000,
                'durability_class' => 'Class 1 (Very Durable)', 'janka_hardness' => 11000,
                'typical_uses' => ['Heavy civil and hydraulic construction', 'Bridges and marine works', 'Railway sleepers', 'Heavy-duty decking', 'Industrial flooring'],
                'commercial_category' => $primary, 'is_promoted' => false,
                'region_availability' => ['East', 'South', 'Centre', 'Littoral'],
            ],
            [
                'slug' => 'azobe',
                'common_name' => 'Azobe',
                'scientific_name' => 'Lophira alata',
                'family' => 'Ochnaceae',
                'trade_names' => ['Ekki', 'Bongossi', 'Red ironwood', 'Azobé'],
                'local_names' => ['Bongossi', 'Akoga'],
                'description' => 'Azobé, known in the trade as Ekki or Bongossi, is one of the heaviest and hardest African hardwoods. Its dark red-brown heartwood carries white deposits in the pores and is exceptionally resistant to abrasion, decay and marine borers. It is the reference timber for lock gates, quays, bridge decks and heavy engineering. Very difficult to work, with high shrinkage and a strong tendency to split — pre-boring is mandatory.',
                'characteristics' => ['Colour' => 'Dark red to chocolate brown with white pore deposits', 'Grain' => 'Interlocked', 'Texture' => 'Coarse', 'Working' => 'Very hard on tools; pre-bore all fixings'],
                'density_kg_m3_min' => 950, 'density_kg_m3_max' => 1150,
                'durability_class' => 'Class 1–2 (Very Durable)', 'janka_hardness' => 14000,
                'typical_uses' => ['Marine and hydraulic construction', 'Bridge decks and quay walls', 'Railway sleepers', 'Heavy-duty industrial flooring', 'Exterior decking'],
                'commercial_category' => $primary, 'is_promoted' => false,
                'region_availability' => ['South-West', 'Littoral', 'South', 'East'],
            ],
            [
                'slug' => 'padouk',
                'common_name' => 'Padouk',
                'scientific_name' => 'Pterocarpus soyauxii',
                'family' => 'Fabaceae',
                'trade_names' => ['African padauk', 'Barwood', 'Camwood', 'Mbel'],
                'local_names' => ['Mbel', 'Ngula'],
                'description' => 'Padouk is instantly recognisable for its vivid orange-red freshly machined surface, which mellows to a warm purple-brown on exposure to light. It is durable, stable and strong, and it turns and finishes beautifully. It is used for flooring, exterior joinery, turnery, tool handles and decorative work. African Pterocarpus populations were added to CITES Appendix II at CoP19.',
                'characteristics' => ['Colour' => 'Bright orange-red ageing to purple-brown', 'Grain' => 'Straight to interlocked', 'Texture' => 'Coarse', 'Movement' => 'Very small — exceptionally stable'],
                'density_kg_m3_min' => 640, 'density_kg_m3_max' => 800,
                'durability_class' => 'Class 1 (Very Durable)', 'janka_hardness' => 7900,
                'typical_uses' => ['Flooring and parquet', 'Exterior joinery', 'Turnery and tool handles', 'Furniture and decorative work', 'Musical instruments'],
                'commercial_category' => $primary, 'is_promoted' => false,
                'is_cites_listed' => true, 'cites_appendix' => 'II',
                'region_availability' => ['East', 'South', 'Centre'],
            ],
            [
                'slug' => 'doussie',
                'common_name' => 'Doussie',
                'scientific_name' => 'Afzelia bipindensis',
                'family' => 'Fabaceae',
                'trade_names' => ['Afzelia', 'Doussié', 'Apa', 'Chanfuta'],
                'local_names' => ['Doussié'],
                'description' => 'Doussié is a stable, very durable reddish-brown hardwood widely used for windows, doors and exterior joinery in demanding climates. Its movement in service is among the smallest of any commercial hardwood, and it holds paint and finishes well. Yellow deposits in the pores can bleed when wetted and may stain adjacent surfaces. African Afzelia populations were added to CITES Appendix II at CoP19.',
                'characteristics' => ['Colour' => 'Reddish brown with yellow pore deposits', 'Grain' => 'Interlocked', 'Texture' => 'Coarse', 'Movement' => 'Very small — outstanding stability'],
                'density_kg_m3_min' => 700, 'density_kg_m3_max' => 850,
                'durability_class' => 'Class 1 (Very Durable)', 'janka_hardness' => 8000,
                'typical_uses' => ['Windows and exterior doors', 'Exterior joinery', 'Flooring and stair treads', 'Boat building', 'Garden furniture'],
                'commercial_category' => $primary, 'is_promoted' => false,
                'is_cites_listed' => true, 'cites_appendix' => 'II',
                'region_availability' => ['East', 'South', 'Centre'],
            ],
            [
                'slug' => 'pachyloba',
                'common_name' => 'Pachyloba',
                'scientific_name' => 'Afzelia pachyloba',
                'family' => 'Fabaceae',
                'trade_names' => ['Afzelia', 'Doussié pachyloba', 'Apa'],
                'local_names' => ['Pachyloba'],
                'description' => 'Pachyloba is traded alongside Doussié under the general Afzelia name and shares its key qualities: high natural durability, very small movement in service and a warm reddish-brown colour. It is typically slightly lighter and paler than Afzelia bipindensis. Used for exterior joinery, flooring and marine applications. African Afzelia populations were added to CITES Appendix II at CoP19.',
                'characteristics' => ['Colour' => 'Light to medium reddish brown', 'Grain' => 'Interlocked', 'Texture' => 'Coarse', 'Movement' => 'Very small'],
                'density_kg_m3_min' => 680, 'density_kg_m3_max' => 830,
                'durability_class' => 'Class 1 (Very Durable)', 'janka_hardness' => 7800,
                'typical_uses' => ['Exterior joinery', 'Windows and doors', 'Flooring', 'Marine and boat work'],
                'commercial_category' => $primary, 'is_promoted' => false,
                'is_cites_listed' => true, 'cites_appendix' => 'II',
                'region_availability' => ['East', 'South', 'Centre'],
            ],
            [
                'slug' => 'movingui',
                'common_name' => 'Movingui',
                'scientific_name' => 'Distemonanthus benthamianus',
                'family' => 'Fabaceae',
                'trade_names' => ['Ayan', 'Nigerian satinwood', 'Bonsamdua', 'Eyen'],
                'local_names' => ['Eyen', 'Movingui'],
                'description' => 'Movingui is a lustrous yellow to yellow-brown hardwood, sometimes with an attractive mottled or wavy figure that earns it the name Nigerian satinwood. It is moderately durable and dimensionally stable, and it takes a high polish. Silica content in some logs blunts cutting edges, so carbide tooling is recommended. Used for joinery, flooring, furniture and decorative veneer.',
                'characteristics' => ['Colour' => 'Lemon yellow to yellow-brown', 'Grain' => 'Interlocked, sometimes wavy', 'Texture' => 'Fine', 'Working' => 'Silica present — use carbide tooling'],
                'density_kg_m3_min' => 650, 'density_kg_m3_max' => 800,
                'durability_class' => 'Class 2 (Durable)', 'janka_hardness' => 6300,
                'typical_uses' => ['Joinery and cabinetwork', 'Flooring and parquet', 'Furniture', 'Decorative veneer', 'Boat building'],
                'commercial_category' => $primary, 'is_promoted' => false,
                'region_availability' => ['South', 'Centre', 'Littoral', 'South-West'],
            ],
            [
                'slug' => 'bilinga',
                'common_name' => 'Bilinga',
                'scientific_name' => 'Nauclea diderrichii',
                'family' => 'Rubiaceae',
                'trade_names' => ['Opepe', 'Aloma', 'Badi', 'Kusia'],
                'local_names' => ['Bilinga', 'Akondoc'],
                'description' => 'Bilinga, traded as Opepe, is a golden-yellow to orange-brown hardwood with high natural durability and good resistance to marine borers. It is a standard timber for harbour and hydraulic works, bridge components, sleepers and heavy exterior joinery. The interlocked grain gives a striped figure on quartered faces, and the wood is moderately hard to work.',
                'characteristics' => ['Colour' => 'Golden yellow to orange-brown', 'Grain' => 'Interlocked', 'Texture' => 'Medium to coarse', 'Durability' => 'Good resistance to marine borers'],
                'density_kg_m3_min' => 700, 'density_kg_m3_max' => 800,
                'durability_class' => 'Class 1 (Very Durable)', 'janka_hardness' => 6500,
                'typical_uses' => ['Harbour and hydraulic works', 'Bridges and heavy construction', 'Railway sleepers', 'Exterior joinery and decking', 'Flooring'],
                'commercial_category' => $primary, 'is_promoted' => false,
                'region_availability' => ['South', 'East', 'Centre', 'South-West'],
            ],
            [
                'slug' => 'okan',
                'common_name' => 'Okan',
                'scientific_name' => 'Cylicodiscus gabunensis',
                'family' => 'Fabaceae',
                'trade_names' => ['Denya', 'Adoum', 'Bokoka', 'African greenheart'],
                'local_names' => ['Okan', 'Adoum'],
                'description' => 'Okan is an extremely dense and very durable yellow-brown to olive hardwood used in the heaviest construction applications. It withstands ground contact, water and abrasion, and is a common substitute for Azobé in hydraulic and civil works. It is difficult to dry without checking and very hard on cutting tools; all fixings must be pre-bored.',
                'characteristics' => ['Colour' => 'Yellow-brown to olive, darkening on exposure', 'Grain' => 'Interlocked', 'Texture' => 'Medium to coarse', 'Drying' => 'Slow — prone to checking'],
                'density_kg_m3_min' => 850, 'density_kg_m3_max' => 1000,
                'durability_class' => 'Class 1 (Very Durable)', 'janka_hardness' => 12000,
                'typical_uses' => ['Heavy civil and hydraulic construction', 'Bridges and piling', 'Railway sleepers', 'Industrial flooring', 'Exterior decking'],
                'commercial_category' => $primary, 'is_promoted' => false,
                'region_availability' => ['East', 'South', 'Centre'],
            ],
            [
                'slug' => 'moabi',
                'common_name' => 'Moabi',
                'scientific_name' => 'Baillonella toxisperma',
                'family' => 'Sapotaceae',
                'trade_names' => ['Moabi', 'African pearwood', 'Muyuka'],
                'local_names' => ['Moabi', 'Adjap'],
                'description' => 'Moabi is a fine-textured, durable pinkish- to reddish-brown hardwood from one of the largest trees of the Cameroonian forest. Its very even texture makes it excellent for precision joinery, sliced veneer and turned work, and it takes an exceptional finish. The tree is also a major source of food oil for forest communities, so supply is socially sensitive and increasingly tightly managed.',
                'characteristics' => ['Colour' => 'Pinkish to reddish brown', 'Grain' => 'Straight to slightly interlocked', 'Texture' => 'Fine and very even', 'Finishing' => 'Takes an excellent polish'],
                'density_kg_m3_min' => 750, 'density_kg_m3_max' => 900,
                'durability_class' => 'Class 2 (Durable)', 'janka_hardness' => 7600,
                'typical_uses' => ['High-grade joinery', 'Flooring and parquet', 'Fine furniture', 'Sliced veneer', 'Turnery'],
                'commercial_category' => $primary, 'is_promoted' => false,
                'region_availability' => ['East', 'South'],
            ],
            [
                'slug' => 'bosse',
                'common_name' => 'Bosse',
                'scientific_name' => 'Guarea cedrata',
                'family' => 'Meliaceae',
                'trade_names' => ['Guarea', 'Bossé clair', 'Scented guarea', 'Obobonufua'],
                'local_names' => ['Bossé'],
                'description' => 'Bossé is a warm pinkish-brown hardwood with a fine texture and a distinctive cedar-like scent. It is stable, moderately durable and works cleanly, making it a well-regarded joinery and cabinet timber. Some logs contain a gummy exudate that can clog abrasives. Widely used for interior fittings, furniture and decorative veneer.',
                'characteristics' => ['Colour' => 'Pinkish brown to light red-brown', 'Grain' => 'Straight to interlocked', 'Texture' => 'Fine', 'Odour' => 'Cedar-like'],
                'density_kg_m3_min' => 550, 'density_kg_m3_max' => 700,
                'durability_class' => 'Class 2–3 (Durable to Moderately Durable)', 'janka_hardness' => 5200,
                'typical_uses' => ['Interior joinery and fittings', 'Furniture and cabinetwork', 'Sliced veneer', 'Flooring', 'Boat building'],
                'commercial_category' => $primary, 'is_promoted' => false,
                'region_availability' => ['East', 'South', 'Centre', 'South-West'],
            ],
            [
                'slug' => 'acajou',
                'common_name' => 'Acajou',
                'scientific_name' => 'Khaya ivorensis',
                'family' => 'Meliaceae',
                'trade_names' => ['African mahogany', 'Khaya', 'Acajou d\'Afrique', 'Ngollon'],
                'local_names' => ['Ngollon', 'Acajou'],
                'description' => 'Khaya ivorensis is the principal African mahogany, a medium-density pinkish- to reddish-brown hardwood with a moderately coarse, lustrous surface. It works and finishes well and is a long-standing furniture, joinery and boat-building timber. It is less durable than the Entandrophragma species and is best kept out of ground contact. African Khaya populations were added to CITES Appendix II at CoP19.',
                'characteristics' => ['Colour' => 'Pink to deep reddish brown', 'Grain' => 'Straight to interlocked', 'Texture' => 'Moderately coarse, lustrous', 'Working' => 'Good, though interlocked grain may tear'],
                'density_kg_m3_min' => 450, 'density_kg_m3_max' => 600,
                'durability_class' => 'Class 3 (Moderately Durable)', 'janka_hardness' => 3600,
                'typical_uses' => ['Furniture and cabinetmaking', 'Interior joinery', 'Boat building', 'Sliced and rotary veneer', 'Musical instruments'],
                'commercial_category' => $primary, 'is_promoted' => false,
                'is_cites_listed' => true, 'cites_appendix' => 'II',
                'region_availability' => ['South', 'Littoral', 'South-West', 'Centre'],
            ],
            [
                'slug' => 'assamela',
                'common_name' => 'Assamela',
                'scientific_name' => 'Pericopsis elata',
                'family' => 'Fabaceae',
                'trade_names' => ['Afrormosia', 'Assamela', 'Kokrodua', 'African teak'],
                'local_names' => ['Assamela', 'Obang'],
                'description' => 'Assamela, better known in the trade as Afrormosia, is a fine-textured yellow-brown hardwood that darkens to a warm teak-like tone. It is very durable, strong and stable, and was long used as a direct teak substitute for furniture, joinery and decking. Pericopsis elata has been listed on CITES Appendix II since 1992, so all international trade requires CITES documentation.',
                'characteristics' => ['Colour' => 'Yellow-brown darkening to teak brown', 'Grain' => 'Straight to interlocked', 'Texture' => 'Fine', 'Note' => 'Contact with iron in damp conditions causes staining'],
                'density_kg_m3_min' => 650, 'density_kg_m3_max' => 800,
                'durability_class' => 'Class 1 (Very Durable)', 'janka_hardness' => 6700,
                'typical_uses' => ['High-grade furniture', 'Exterior and interior joinery', 'Decking and garden furniture', 'Flooring', 'Boat building'],
                'commercial_category' => $specialty, 'is_promoted' => false,
                'is_cites_listed' => true, 'cites_appendix' => 'II',
                'region_availability' => ['East', 'South'],
            ],
            [
                'slug' => 'bubinga',
                'common_name' => 'Bubinga',
                'scientific_name' => 'Guibourtia tessmannii',
                'family' => 'Fabaceae',
                'trade_names' => ['Kevazingo', 'African rosewood', 'Essingang', 'Waka'],
                'local_names' => ['Essingang', 'Kevazingo'],
                'description' => 'Bubinga is a heavy, lustrous red-brown hardwood with darker purple veining and often spectacular figure — pommele, waterfall and quilted patterns are highly sought for veneer. It is dense, strong and moderately durable, and takes a superb polish. Sold for fine furniture, luxury veneer, turnery and musical instruments. Guibourtia tessmannii is listed on CITES Appendix II, so international trade requires permits.',
                'characteristics' => ['Colour' => 'Pinkish to dark red-brown with purple veining', 'Grain' => 'Straight to interlocked, often figured', 'Texture' => 'Fine to medium', 'Figure' => 'Pommele, waterfall and quilted figure common'],
                'density_kg_m3_min' => 850, 'density_kg_m3_max' => 1000,
                'durability_class' => 'Class 2–3 (Durable to Moderately Durable)', 'janka_hardness' => 10700,
                'typical_uses' => ['Fine furniture', 'Luxury decorative veneer', 'Musical instruments', 'Turnery and knife handles', 'Live-edge slabs and tabletops'],
                'commercial_category' => $specialty, 'is_promoted' => false,
                'is_cites_listed' => true, 'cites_appendix' => 'II',
                'region_availability' => ['South', 'East', 'Centre'],
            ],
            [
                'slug' => 'wenge',
                'common_name' => 'Wenge',
                'scientific_name' => 'Millettia laurentii',
                'family' => 'Fabaceae',
                'trade_names' => ['Wengé', 'Panga panga', 'Dikela', 'Awong'],
                'local_names' => ['Awong', 'Wengé'],
                'description' => 'Wengé is a very dark chocolate-brown to near-black hardwood marked by fine, close black lines that give it its unmistakable striped look. It is dense, durable and strong, and is a premium choice for dark flooring, panelling, furniture and turnery. The coarse texture and brittle splinters make it demanding to work, and the fine dust is a known irritant.',
                'characteristics' => ['Colour' => 'Dark chocolate brown with fine black veining', 'Grain' => 'Straight', 'Texture' => 'Coarse', 'Handling' => 'Splinters and dust are irritant'],
                'density_kg_m3_min' => 800, 'density_kg_m3_max' => 950,
                'durability_class' => 'Class 1–2 (Very Durable)', 'janka_hardness' => 8600,
                'typical_uses' => ['High-end flooring', 'Wall panelling', 'Furniture and cabinetwork', 'Turnery and musical instruments', 'Decorative veneer'],
                'commercial_category' => $specialty, 'is_promoted' => false,
                'region_availability' => ['East', 'South'],
            ],
            [
                'slug' => 'ebene',
                'common_name' => 'Ebene',
                'scientific_name' => 'Diospyros crassiflora',
                'family' => 'Ebenaceae',
                'trade_names' => ['African ebony', 'Gabon ebony', 'Ébène', 'Mevini'],
                'local_names' => ['Mevini', 'Ébène'],
                'description' => 'African ebony is the classic jet-black cabinet wood, extremely dense, fine-textured and capable of a mirror polish. Heartwood is uniformly black or black with faint brown streaks; the sapwood is pale and sharply contrasting. It is sold in small squares and billets for instrument parts, inlay, turnery and knife scales. Note that the CITES Diospyros listing covers Madagascar populations — this Cameroonian species is not itself CITES-listed, but sourcing should still be verified.',
                'characteristics' => ['Colour' => 'Jet black, occasionally with brown streaks', 'Grain' => 'Straight to slightly interlocked', 'Texture' => 'Very fine', 'Working' => 'Very hard; blunts tools rapidly'],
                'density_kg_m3_min' => 900, 'density_kg_m3_max' => 1100,
                'durability_class' => 'Class 1 (Very Durable)', 'janka_hardness' => 14000,
                'typical_uses' => ['Musical instrument parts', 'Inlay and marquetry', 'Turnery and knife handles', 'Carving', 'Luxury small goods'],
                'commercial_category' => $specialty, 'is_promoted' => false,
                'region_availability' => ['East', 'South', 'Centre'],
            ],
            [
                'slug' => 'zingana',
                'common_name' => 'Zingana',
                'scientific_name' => 'Microberlinia bisulcata',
                'family' => 'Fabaceae',
                'trade_names' => ['Zebrawood', 'Zebrano', 'Allen ele'],
                'local_names' => ['Zingana'],
                'description' => 'Zingana, sold internationally as Zebrawood, is a pale golden hardwood crossed by bold dark brown to black stripes — one of the most distinctive figures in the trade. The wood is dense and hard with a coarse, interlocked grain that requires careful machining. It is used almost entirely for decorative purposes: veneer, panelling, furniture accents and turnery. Its natural range is very restricted, concentrated in south-west Cameroon.',
                'characteristics' => ['Colour' => 'Pale gold with dark brown-black stripes', 'Grain' => 'Interlocked and wavy', 'Texture' => 'Coarse', 'Note' => 'Very restricted natural range'],
                'density_kg_m3_min' => 700, 'density_kg_m3_max' => 850,
                'durability_class' => 'Class 3 (Moderately Durable)', 'janka_hardness' => 8000,
                'typical_uses' => ['Decorative veneer and panelling', 'Furniture accents and inlay', 'Turnery', 'Automotive interior trim'],
                'commercial_category' => $specialty, 'is_promoted' => false,
                'region_availability' => ['South-West', 'Littoral'],
            ],
            [
                'slug' => 'douka',
                'common_name' => 'Douka',
                'scientific_name' => 'Tieghemella africana',
                'family' => 'Sapotaceae',
                'trade_names' => ['Makore', 'Douka', 'Baku', 'African cherry'],
                'local_names' => ['Douka'],
                'description' => 'Douka is traded with Makoré and is a fine-textured pink to blood-red hardwood, sometimes with a shimmering mottled figure that is highly valued in veneer. It is durable, stable and takes a very high finish, and is used for quality joinery, furniture, flooring and boat work. Silica in some logs blunts tooling, and the fine dust is a recognised respiratory irritant.',
                'characteristics' => ['Colour' => 'Pink to deep blood red', 'Grain' => 'Straight to slightly wavy', 'Texture' => 'Fine and even', 'Working' => 'Silica present; dust is irritant'],
                'density_kg_m3_min' => 600, 'density_kg_m3_max' => 750,
                'durability_class' => 'Class 2 (Durable)', 'janka_hardness' => 5700,
                'typical_uses' => ['High-grade joinery', 'Furniture and cabinetwork', 'Decorative veneer', 'Flooring', 'Boat building'],
                'commercial_category' => $primary, 'is_promoted' => false,
                'region_availability' => ['South', 'East', 'Littoral'],
            ],
            [
                'slug' => 'okoume',
                'common_name' => 'Okoume',
                'scientific_name' => 'Aucoumea klaineana',
                'family' => 'Burseraceae',
                'trade_names' => ['Okoumé', 'Gaboon', 'Gabon mahogany', 'Angouma'],
                'local_names' => ['Angouma', 'Okoumé'],
                'description' => 'Okoumé is a light salmon-pink hardwood that peels exceptionally well and is the world\'s principal plywood species, including the marine plywood used in boat building. It is lightweight, easy to work and finishes smoothly, but it is not naturally durable and contains silica that dulls tools. In Cameroon it occurs mainly in the coastal and southern forests bordering Gabon and Equatorial Guinea.',
                'characteristics' => ['Colour' => 'Salmon pink to light pinkish brown', 'Grain' => 'Straight to slightly wavy', 'Texture' => 'Medium and even', 'Working' => 'Silica present — carbide tooling advised'],
                'density_kg_m3_min' => 350, 'density_kg_m3_max' => 500,
                'durability_class' => 'Class 4–5 (Slightly to Not Durable)', 'janka_hardness' => 1900,
                'typical_uses' => ['Plywood and marine plywood', 'Rotary veneer', 'Light joinery and furniture parts', 'Boat hulls and decks', 'Packaging'],
                'commercial_category' => $primary, 'is_promoted' => false,
                'region_availability' => ['South', 'Littoral'],
            ],
            [
                'slug' => 'niangon',
                'common_name' => 'Niangon',
                'scientific_name' => 'Heritiera utilis',
                'family' => 'Malvaceae',
                'trade_names' => ['Niangon', 'Nyankom', 'Ogoue', 'Whismore'],
                'local_names' => ['Niangon'],
                'description' => 'Niangon is a reddish-brown hardwood with a coarse texture and a characteristic greasy or waxy feel from natural resin content. It is durable and stable enough for exterior joinery, and the resin gives good weather resistance, though it can interfere with gluing and finishing unless surfaces are degreased. Commonly used for windows, doors, cladding and boat work.',
                'characteristics' => ['Colour' => 'Reddish brown', 'Grain' => 'Interlocked', 'Texture' => 'Coarse', 'Note' => 'Waxy resin — degrease before gluing or finishing'],
                'density_kg_m3_min' => 560, 'density_kg_m3_max' => 750,
                'durability_class' => 'Class 2–3 (Durable to Moderately Durable)', 'janka_hardness' => 4700,
                'typical_uses' => ['Windows and exterior joinery', 'Cladding', 'Boat building', 'Interior fittings', 'Flooring'],
                'commercial_category' => $primary, 'is_promoted' => false,
                'region_availability' => ['South-West', 'Littoral'],
            ],
            [
                'slug' => 'frake',
                'common_name' => 'Frake',
                'scientific_name' => 'Terminalia superba',
                'family' => 'Combretaceae',
                'trade_names' => ['Limba', 'Afara', 'White limba', 'Korina'],
                'local_names' => ['Fraké', 'Akom'],
                'description' => 'Fraké, sold as Limba or Afara, is a pale straw-coloured, lightweight hardwood that machines and peels very cleanly. Logs with a dark heart streak are marketed as "black limba" and used decoratively, notably for guitar bodies. It is easy to dry and work but is not durable and needs protection outdoors. Used heavily for plywood, joinery and furniture components.',
                'characteristics' => ['Colour' => 'Pale straw, sometimes with dark heart streaks', 'Grain' => 'Straight to slightly interlocked', 'Texture' => 'Medium to coarse', 'Working' => 'Very easy to machine and peel'],
                'density_kg_m3_min' => 450, 'density_kg_m3_max' => 580,
                'durability_class' => 'Class 4–5 (Slightly to Not Durable)', 'janka_hardness' => 2700,
                'typical_uses' => ['Plywood and veneer', 'Interior joinery and mouldings', 'Furniture components', 'Musical instrument bodies', 'Packaging'],
                'commercial_category' => $primary, 'is_promoted' => false,
                'region_availability' => ['East', 'Centre', 'South', 'Littoral'],
            ],
            [
                'slug' => 'framire',
                'common_name' => 'Framire',
                'scientific_name' => 'Terminalia ivorensis',
                'family' => 'Combretaceae',
                'trade_names' => ['Idigbo', 'Framiré', 'Emeri', 'Black afara'],
                'local_names' => ['Framiré'],
                'description' => 'Framiré, traded as Idigbo, is a light yellow-brown hardwood that is stable, easy to work and surprisingly durable for its weight. It is a long-standing joinery timber for windows, doors and interior trim. Yellow extractives can leach out and stain masonry or react with iron fixings in damp conditions, so stainless or galvanised fixings are preferred.',
                'characteristics' => ['Colour' => 'Pale yellow-brown', 'Grain' => 'Straight to slightly irregular', 'Texture' => 'Medium to coarse', 'Note' => 'Extractives can stain masonry and corrode iron'],
                'density_kg_m3_min' => 480, 'density_kg_m3_max' => 620,
                'durability_class' => 'Class 2 (Durable)', 'janka_hardness' => 3700,
                'typical_uses' => ['Windows and exterior joinery', 'Doors and interior trim', 'Furniture', 'Veneer', 'Light construction'],
                'commercial_category' => $primary, 'is_promoted' => false,
                'region_availability' => ['East', 'Centre', 'South-West'],
            ],
            [
                'slug' => 'dabema',
                'common_name' => 'Dabema',
                'scientific_name' => 'Piptadeniastrum africanum',
                'family' => 'Fabaceae',
                'trade_names' => ['Dahoma', 'Agboin', 'Ekhimi', 'Bokungu'],
                'local_names' => ['Atui', 'Dabéma'],
                'description' => 'Dabema, traded as Dahoma, is a strong yellow-brown to golden hardwood used for general and heavy construction, sleepers and exterior carpentry. It is moderately durable and hard-wearing, though it dries slowly with a tendency to distort. The dust is a well-documented irritant and good extraction is essential when machining.',
                'characteristics' => ['Colour' => 'Yellow-brown to golden brown', 'Grain' => 'Interlocked', 'Texture' => 'Coarse', 'Handling' => 'Dust is a strong irritant'],
                'density_kg_m3_min' => 600, 'density_kg_m3_max' => 800,
                'durability_class' => 'Class 3 (Moderately Durable)', 'janka_hardness' => 6500,
                'typical_uses' => ['General and heavy construction', 'Railway sleepers', 'Exterior carpentry', 'Flooring', 'Plywood'],
                'commercial_category' => $primary, 'is_promoted' => false,
                'region_availability' => ['East', 'Centre', 'South'],
            ],
            [
                'slug' => 'mukulungu',
                'common_name' => 'Mukulungu',
                'scientific_name' => 'Autranella congolensis',
                'family' => 'Sapotaceae',
                'trade_names' => ['Mukulungu', 'Elang', 'Autranella'],
                'local_names' => ['Elang', 'Mukulungu'],
                'description' => 'Mukulungu is a very dense, very durable dark red-brown hardwood related to Moabi. It is highly resistant to decay and insects and is used for heavy construction, hydraulic works, sleepers and exterior decking. It is difficult to dry and hard on tools, and the fine dust can be irritant. Traded in smaller volumes than the flagship species.',
                'characteristics' => ['Colour' => 'Dark red-brown', 'Grain' => 'Straight to interlocked', 'Texture' => 'Fine to medium', 'Drying' => 'Difficult — prone to checking and distortion'],
                'density_kg_m3_min' => 850, 'density_kg_m3_max' => 1000,
                'durability_class' => 'Class 1–2 (Very Durable)', 'janka_hardness' => 11000,
                'typical_uses' => ['Heavy construction and hydraulic works', 'Railway sleepers', 'Exterior decking', 'Industrial flooring', 'Marine works'],
                'commercial_category' => $secondary, 'is_promoted' => false,
                'region_availability' => ['East', 'South'],
            ],
            [
                'slug' => 'kotibe',
                'common_name' => 'Kotibe',
                'scientific_name' => 'Nesogordonia papaverifera',
                'family' => 'Malvaceae',
                'trade_names' => ['Danta', 'Kotibé', 'Otutu', 'Aborbora'],
                'local_names' => ['Kotibé'],
                'description' => 'Kotibé, traded as Danta, is a tough reddish-brown hardwood with a fine texture and high resistance to shock and abrasion. It is a favoured timber for tool handles, sports goods, vehicle bodies and hard-wearing flooring. It works reasonably well but the interlocked grain tears if tooling is not sharp.',
                'characteristics' => ['Colour' => 'Reddish brown', 'Grain' => 'Interlocked', 'Texture' => 'Fine', 'Strength' => 'Very high shock resistance'],
                'density_kg_m3_min' => 700, 'density_kg_m3_max' => 830,
                'durability_class' => 'Class 2–3 (Durable to Moderately Durable)', 'janka_hardness' => 6700,
                'typical_uses' => ['Flooring and stair treads', 'Tool handles and sports goods', 'Vehicle bodies', 'Furniture', 'Joinery'],
                'commercial_category' => $secondary, 'is_promoted' => false,
                'region_availability' => ['East', 'Centre', 'South'],
            ],
            [
                'slug' => 'bete',
                'common_name' => 'Bete',
                'scientific_name' => 'Mansonia altissima',
                'family' => 'Malvaceae',
                'trade_names' => ['Mansonia', 'African black walnut', 'Bété', 'Aprono'],
                'local_names' => ['Bété'],
                'description' => 'Bété, traded as Mansonia, is a grey-brown to purple-brown hardwood often used as a walnut substitute for furniture and decorative veneer. It is durable, stable and works to a very clean finish. The dust is notably irritant and toxic to some workers, so extraction and respiratory protection are important.',
                'characteristics' => ['Colour' => 'Grey-brown to purple-brown, fading with light', 'Grain' => 'Straight', 'Texture' => 'Fine', 'Handling' => 'Dust is a known irritant — use protection'],
                'density_kg_m3_min' => 550, 'density_kg_m3_max' => 700,
                'durability_class' => 'Class 1–2 (Very Durable)', 'janka_hardness' => 4900,
                'typical_uses' => ['Furniture and cabinetwork', 'Decorative veneer', 'Interior joinery', 'Turnery', 'Gun stocks'],
                'commercial_category' => $secondary, 'is_promoted' => false,
                'region_availability' => ['East', 'Centre', 'South-West'],
            ],
            [
                'slug' => 'aningre',
                'common_name' => 'Aningre',
                'scientific_name' => 'Pouteria spp. (Aningeria spp.)',
                'family' => 'Sapotaceae',
                'trade_names' => ['Aningeria', 'Anegre', 'Aniegre', 'Tanganyika nut'],
                'local_names' => ['Aningré'],
                'description' => 'Aningré is a pale cream to light pinkish-brown hardwood with a fine, even texture and a soft lustre. Figured logs with a mottled or wavy grain are highly valued for decorative veneer and luxury interiors. The wood is not durable and contains silica that dulls tooling, so it is used for interior work: furniture, panelling and plywood faces.',
                'characteristics' => ['Colour' => 'Cream to light pinkish brown', 'Grain' => 'Straight to wavy', 'Texture' => 'Fine and even', 'Working' => 'Silica present — carbide tooling advised'],
                'density_kg_m3_min' => 480, 'density_kg_m3_max' => 650,
                'durability_class' => 'Class 4–5 (Slightly to Not Durable)', 'janka_hardness' => 4200,
                'typical_uses' => ['Decorative veneer and panelling', 'Furniture', 'Plywood faces', 'Interior joinery'],
                'commercial_category' => $secondary, 'is_promoted' => false,
                'region_availability' => ['East', 'South', 'Centre'],
            ],
            [
                'slug' => 'ilomba',
                'common_name' => 'Ilomba',
                'scientific_name' => 'Pycnanthus angolensis',
                'family' => 'Myristicaceae',
                'trade_names' => ['Ilomba', 'Otie', 'Akomu', 'False nutmeg'],
                'local_names' => ['Eteng', 'Ilomba'],
                'description' => 'Ilomba is a pale pinkish-grey hardwood of low density that peels and glues very well, making it a workhorse for plywood, blockboard and interior utility work. It has no natural durability and is very susceptible to blue stain and insect attack, so logs must be processed and treated promptly after felling.',
                'characteristics' => ['Colour' => 'Pale pinkish grey', 'Grain' => 'Straight', 'Texture' => 'Medium to coarse', 'Note' => 'Highly prone to blue stain — process quickly'],
                'density_kg_m3_min' => 400, 'density_kg_m3_max' => 550,
                'durability_class' => 'Class 5 (Not Durable)', 'janka_hardness' => 2700,
                'typical_uses' => ['Plywood and blockboard', 'Rotary veneer', 'Interior joinery', 'Furniture components', 'Packaging'],
                'commercial_category' => $secondary, 'is_promoted' => false,
                'region_availability' => ['East', 'Centre', 'South', 'Littoral'],
            ],
            [
                'slug' => 'abura',
                'common_name' => 'Abura',
                'scientific_name' => 'Mitragyna ciliata',
                'family' => 'Rubiaceae',
                'trade_names' => ['Abura', 'Bahia', 'Subaha', 'Elelom'],
                'local_names' => ['Elelom', 'Abura'],
                'description' => 'Abura is a pale pinkish-brown, fine and even-textured hardwood that machines and carves exceptionally cleanly. It is dimensionally stable and takes stain well, so it is used for mouldings, interior trim, drawing boards, laboratory fittings and pattern making. It is not durable and can contain silica, which dulls cutting edges.',
                'characteristics' => ['Colour' => 'Pale pinkish brown', 'Grain' => 'Straight to slightly interlocked', 'Texture' => 'Fine and even', 'Working' => 'Machines and carves cleanly'],
                'density_kg_m3_min' => 480, 'density_kg_m3_max' => 620,
                'durability_class' => 'Class 4 (Slightly Durable)', 'janka_hardness' => 2700,
                'typical_uses' => ['Mouldings and interior trim', 'Pattern making', 'Laboratory and drawing furniture', 'Carving', 'Plywood'],
                'commercial_category' => $promoted, 'is_promoted' => true,
                'region_availability' => ['Littoral', 'South-West', 'South'],
            ],
            [
                'slug' => 'longhi',
                'common_name' => 'Longhi',
                'scientific_name' => 'Gambeya africana',
                'family' => 'Sapotaceae',
                'trade_names' => ['Longhi', 'Longhi blanc', 'Abam', 'African star apple'],
                'local_names' => ['Abam', 'Longhi'],
                'description' => 'Longhi is a pale pinkish to light brown hardwood with a fine, even texture, traded in modest volumes as an alternative to the heavier Sapotaceae. It works and finishes well and is used for joinery, furniture, mouldings and sliced veneer. Natural durability is limited, so it is best kept to interior and protected applications.',
                'characteristics' => ['Colour' => 'Pale pink to light brown', 'Grain' => 'Straight to slightly interlocked', 'Texture' => 'Fine and even', 'Working' => 'Good — finishes smoothly'],
                'density_kg_m3_min' => 600, 'density_kg_m3_max' => 750,
                'durability_class' => 'Class 3–4 (Moderately to Slightly Durable)', 'janka_hardness' => 5000,
                'typical_uses' => ['Interior joinery', 'Furniture', 'Mouldings', 'Sliced veneer'],
                'commercial_category' => $promoted, 'is_promoted' => true,
                'region_availability' => ['East', 'South', 'Centre'],
            ],
            [
                'slug' => 'niove',
                'common_name' => 'Niove',
                'scientific_name' => 'Staudtia kamerunensis',
                'family' => 'Myristicaceae',
                'trade_names' => ['Niové', 'Menga menga', 'Susu', 'Molubi'],
                'local_names' => ['Menga menga', 'Niové'],
                'description' => 'Niové is a dense orange-red to dark red hardwood with a very fine texture and a distinctive waxy feel. It is durable and hard-wearing, and is used for flooring, turnery, joinery and decorative work. The natural oils can slow drying of finishes and interfere with gluing unless surfaces are prepared. Traded as a promoted lesser-known species.',
                'characteristics' => ['Colour' => 'Orange-red to dark red', 'Grain' => 'Straight to slightly interlocked', 'Texture' => 'Very fine', 'Note' => 'Oily — degrease before gluing or finishing'],
                'density_kg_m3_min' => 800, 'density_kg_m3_max' => 950,
                'durability_class' => 'Class 2 (Durable)', 'janka_hardness' => 8000,
                'typical_uses' => ['Flooring and parquet', 'Turnery', 'Joinery', 'Decorative work and inlay', 'Tool handles'],
                'commercial_category' => $promoted, 'is_promoted' => true,
                'region_availability' => ['East', 'South', 'Centre'],
            ],
            [
                'slug' => 'eyong',
                'common_name' => 'Eyong',
                'scientific_name' => 'Eribroma oblongum',
                'family' => 'Malvaceae',
                'trade_names' => ['Eyong', 'Ohia', 'Bongele', 'Kondofindo'],
                'local_names' => ['Eyong'],
                'description' => 'Eyong is a pale yellowish to light brown hardwood of medium density, traded as a lesser-known species suited to interior joinery, furniture parts and plywood. It works easily and finishes acceptably, but it has little natural durability and is susceptible to blue stain, so prompt processing and preservative treatment matter.',
                'characteristics' => ['Colour' => 'Pale yellow to light brown', 'Grain' => 'Straight to interlocked', 'Texture' => 'Medium', 'Note' => 'Susceptible to blue stain'],
                'density_kg_m3_min' => 550, 'density_kg_m3_max' => 700,
                'durability_class' => 'Class 4 (Slightly Durable)', 'janka_hardness' => 4500,
                'typical_uses' => ['Interior joinery', 'Furniture components', 'Plywood', 'Light construction'],
                'commercial_category' => $promoted, 'is_promoted' => true,
                'region_availability' => ['East', 'South', 'Centre'],
            ],
            [
                'slug' => 'ozigo',
                'common_name' => 'Ozigo',
                'scientific_name' => 'Dacryodes buettneri',
                'family' => 'Burseraceae',
                'trade_names' => ['Ozigo', 'Assia', 'Igaganga'],
                'local_names' => ['Ozigo', 'Assia'],
                'description' => 'Ozigo is a pale pinkish-brown, medium-density hardwood related to Okoumé and used in much the same way — mainly for rotary veneer and plywood. It peels cleanly and glues well but is only slightly durable and can contain resin pockets. A lesser-known species promoted as a plywood and light-joinery timber.',
                'characteristics' => ['Colour' => 'Pale pinkish brown', 'Grain' => 'Straight to slightly wavy', 'Texture' => 'Medium', 'Note' => 'Resin pockets occur in some logs'],
                'density_kg_m3_min' => 500, 'density_kg_m3_max' => 650,
                'durability_class' => 'Class 4 (Slightly Durable)', 'janka_hardness' => 3600,
                'typical_uses' => ['Rotary veneer and plywood', 'Light joinery', 'Furniture components', 'Packaging'],
                'commercial_category' => $promoted, 'is_promoted' => true,
                'region_availability' => ['South', 'East'],
            ],
            [
                'slug' => 'tchitola',
                'common_name' => 'Tchitola',
                'scientific_name' => 'Oxystigma oxyphyllum',
                'family' => 'Fabaceae',
                'trade_names' => ['Tchitola', 'Lolagbola', 'Tola branca'],
                'local_names' => ['Tchitola'],
                'description' => 'Tchitola is a reddish-brown hardwood with darker streaking and a coarse texture, often carrying resin canals that appear as fine dark lines. It is moderately durable and used for joinery, furniture and decorative veneer where a mahogany-like appearance is wanted at lower cost. Resin can gum abrasives and interfere with finishing.',
                'characteristics' => ['Colour' => 'Reddish brown with darker streaks', 'Grain' => 'Straight to interlocked', 'Texture' => 'Coarse', 'Note' => 'Resin canals may gum tooling'],
                'density_kg_m3_min' => 550, 'density_kg_m3_max' => 700,
                'durability_class' => 'Class 3 (Moderately Durable)', 'janka_hardness' => 4300,
                'typical_uses' => ['Interior joinery', 'Furniture', 'Decorative veneer', 'Plywood'],
                'commercial_category' => $promoted, 'is_promoted' => true,
                'region_availability' => ['East', 'South'],
            ],
            [
                'slug' => 'ebiara',
                'common_name' => 'Ebiara',
                'scientific_name' => 'Berlinia bracteosa',
                'family' => 'Fabaceae',
                'trade_names' => ['Ebiara', 'Red zebrawood', 'Ekpogoi', 'Berlinia'],
                'local_names' => ['Ebiara'],
                'description' => 'Ebiara is a reddish-brown hardwood marked with darker purple-red streaks that give sawn faces a striking striped appearance, hence the trade name red zebrawood. It is dense and moderately durable, working reasonably well despite interlocked grain. Used for flooring, joinery, furniture and decorative veneer.',
                'characteristics' => ['Colour' => 'Red-brown with darker purple-red streaks', 'Grain' => 'Interlocked', 'Texture' => 'Coarse', 'Figure' => 'Pronounced stripe on quartered faces'],
                'density_kg_m3_min' => 650, 'density_kg_m3_max' => 800,
                'durability_class' => 'Class 2–3 (Durable to Moderately Durable)', 'janka_hardness' => 7000,
                'typical_uses' => ['Flooring', 'Interior joinery', 'Furniture', 'Decorative veneer'],
                'commercial_category' => $promoted, 'is_promoted' => true,
                'region_availability' => ['South', 'East', 'Littoral'],
            ],
            [
                'slug' => 'lati',
                'common_name' => 'Lati',
                'scientific_name' => 'Amphimas pterocarpoides',
                'family' => 'Fabaceae',
                'trade_names' => ['Lati', 'Bokanga', 'Edzui', 'Yaya'],
                'local_names' => ['Edzui', 'Lati'],
                'description' => 'Lati is a yellow-brown to light brown hardwood of medium to high density with a coarse texture and interlocked grain. It is moderately durable and reasonably strong, and is promoted for general construction, joinery, flooring and plywood. Drying needs care as the wood is prone to distortion.',
                'characteristics' => ['Colour' => 'Yellow-brown to light brown', 'Grain' => 'Interlocked', 'Texture' => 'Coarse', 'Drying' => 'Prone to distortion — dry slowly'],
                'density_kg_m3_min' => 650, 'density_kg_m3_max' => 800,
                'durability_class' => 'Class 3 (Moderately Durable)', 'janka_hardness' => 6000,
                'typical_uses' => ['General construction', 'Joinery', 'Flooring', 'Plywood', 'Furniture components'],
                'commercial_category' => $promoted, 'is_promoted' => true,
                'region_availability' => ['East', 'Centre', 'South'],
            ],
            [
                'slug' => 'kanda',
                'common_name' => 'Kanda',
                'scientific_name' => 'Beilschmiedia spp.',
                'family' => 'Lauraceae',
                'trade_names' => ['Kanda', 'Kanda brun', 'Kanda rose'],
                'local_names' => ['Kanda'],
                'description' => 'Kanda covers several Beilschmiedia species traded together, ranging from pinkish to grey-brown in colour with a fine to medium texture. The wood is moderately dense and works well, and is promoted for joinery, furniture and light construction. Durability is limited, so exterior use calls for preservative treatment.',
                'characteristics' => ['Colour' => 'Pink to grey-brown', 'Grain' => 'Straight to slightly interlocked', 'Texture' => 'Fine to medium', 'Note' => 'Several species traded under one name'],
                'density_kg_m3_min' => 600, 'density_kg_m3_max' => 780,
                'durability_class' => 'Class 3–4 (Moderately to Slightly Durable)', 'janka_hardness' => 6000,
                'typical_uses' => ['Interior joinery', 'Furniture', 'Light construction', 'Flooring'],
                'commercial_category' => $promoted, 'is_promoted' => true,
                'region_availability' => ['East', 'South', 'Centre'],
            ],
            [
                'slug' => 'onzabili',
                'common_name' => 'Onzabili',
                'scientific_name' => 'Antrocaryon klaineanum',
                'family' => 'Anacardiaceae',
                'trade_names' => ['Onzabili', 'Angongui', 'Mouambe'],
                'local_names' => ['Onzabili', 'Angongui'],
                'description' => 'Onzabili is a pinkish to light reddish-brown hardwood of medium density with a fairly coarse texture. It works easily and is promoted for interior joinery, furniture and plywood. Natural durability is moderate and the sapwood is prone to blue stain, so logs are best converted promptly.',
                'characteristics' => ['Colour' => 'Pink to light reddish brown', 'Grain' => 'Straight to slightly interlocked', 'Texture' => 'Medium to coarse', 'Note' => 'Sapwood prone to blue stain'],
                'density_kg_m3_min' => 550, 'density_kg_m3_max' => 700,
                'durability_class' => 'Class 3 (Moderately Durable)', 'janka_hardness' => 5500,
                'typical_uses' => ['Interior joinery', 'Furniture', 'Plywood and veneer', 'Light construction'],
                'commercial_category' => $promoted, 'is_promoted' => true,
                'region_availability' => ['East', 'South', 'Centre'],
            ],
            [
                'slug' => 'divida',
                'common_name' => 'Divida',
                'scientific_name' => 'Scorodophloeus zenkeri',
                'family' => 'Fabaceae',
                'trade_names' => ['Divida', 'Olon', 'Garlic tree'],
                'local_names' => ['Olon', 'Divida'],
                'description' => 'Divida is a dense yellow-brown to reddish hardwood whose freshly cut wood carries a strong garlic-like odour that fades on drying. It is durable and hard-wearing, and is promoted for flooring, joinery and heavy interior work. The high density makes it demanding to machine and fixings should be pre-bored.',
                'characteristics' => ['Colour' => 'Yellow-brown to reddish brown', 'Grain' => 'Interlocked', 'Texture' => 'Fine to medium', 'Odour' => 'Strong garlic smell when freshly cut'],
                'density_kg_m3_min' => 800, 'density_kg_m3_max' => 950,
                'durability_class' => 'Class 2 (Durable)', 'janka_hardness' => 8000,
                'typical_uses' => ['Flooring and parquet', 'Joinery', 'Turnery', 'Heavy interior work'],
                'commercial_category' => $promoted, 'is_promoted' => true,
                'region_availability' => ['East', 'South', 'Centre'],
            ],
            [
                'slug' => 'faro',
                'common_name' => 'Faro',
                'scientific_name' => 'Daniellia ogea',
                'family' => 'Fabaceae',
                'trade_names' => ['Faro', 'Ogea', 'Daniellia', 'Oziya'],
                'local_names' => ['Faro'],
                'description' => 'Faro is a pale pinkish-brown, relatively light hardwood that dries quickly and works easily. It is used for interior joinery, furniture parts, plywood and packaging. The tree yields an aromatic gum resin, and resin traces in the wood can affect finishing. Durability is low, so exterior use requires treatment.',
                'characteristics' => ['Colour' => 'Pale pinkish brown', 'Grain' => 'Straight to interlocked', 'Texture' => 'Medium to coarse', 'Note' => 'Aromatic gum resin present in some logs'],
                'density_kg_m3_min' => 450, 'density_kg_m3_max' => 600,
                'durability_class' => 'Class 4 (Slightly Durable)', 'janka_hardness' => 3500,
                'typical_uses' => ['Interior joinery', 'Furniture components', 'Plywood and veneer', 'Packaging'],
                'commercial_category' => $promoted, 'is_promoted' => true,
                'region_availability' => ['East', 'Centre', 'South'],
            ],
            [
                'slug' => 'bodioa',
                'common_name' => 'Bodioa',
                'scientific_name' => 'Anopyxis klaineana',
                'family' => 'Rhizophoraceae',
                'trade_names' => ['Bodioa', 'Kokoti', 'Anopyxis'],
                'local_names' => ['Bodioa', 'Kokoti'],
                'description' => 'Bodioa is a pale yellow-brown to pinkish hardwood of medium to high density with good strength. It is promoted for general construction, joinery and flooring. Drying can be slow and the wood is prone to checking, so careful kiln schedules are needed. Moderate natural durability limits unprotected exterior use.',
                'characteristics' => ['Colour' => 'Pale yellow-brown to pinkish', 'Grain' => 'Interlocked', 'Texture' => 'Fine to medium', 'Drying' => 'Slow — prone to checking'],
                'density_kg_m3_min' => 650, 'density_kg_m3_max' => 820,
                'durability_class' => 'Class 3 (Moderately Durable)', 'janka_hardness' => 6500,
                'typical_uses' => ['General construction', 'Joinery', 'Flooring', 'Furniture'],
                'commercial_category' => $promoted, 'is_promoted' => true,
                'region_availability' => ['South-West', 'Littoral', 'South'],
            ],
            [
                'slug' => 'alep',
                'common_name' => 'Alep',
                'scientific_name' => 'Desbordesia glaucescens',
                'family' => 'Irvingiaceae',
                'trade_names' => ['Alep', 'Omang', 'Ekop-alep'],
                'local_names' => ['Alep', 'Omang'],
                'description' => 'Alep is a very dense, pale yellow to light brown hardwood, hard and strong but demanding to dry and to machine. It is promoted for heavy construction, flooring and sleepers where great strength is needed. Rapid drying causes severe checking, so slow schedules and end sealing are essential.',
                'characteristics' => ['Colour' => 'Pale yellow to light brown', 'Grain' => 'Interlocked', 'Texture' => 'Fine to medium', 'Drying' => 'Very difficult — severe checking risk'],
                'density_kg_m3_min' => 850, 'density_kg_m3_max' => 1000,
                'durability_class' => 'Class 3 (Moderately Durable)', 'janka_hardness' => 10000,
                'typical_uses' => ['Heavy construction', 'Industrial flooring', 'Railway sleepers', 'Tool handles'],
                'commercial_category' => $promoted, 'is_promoted' => true,
                'region_availability' => ['East', 'South', 'Centre'],
            ],
            [
                'slug' => 'eveuss',
                'common_name' => 'Eveuss',
                'scientific_name' => 'Klainedoxa gabonensis',
                'family' => 'Irvingiaceae',
                'trade_names' => ['Eveuss', 'Kroma', 'Bodwe', 'Ngon'],
                'local_names' => ['Eveuss', 'Ngon'],
                'description' => 'Eveuss is an exceptionally dense and hard reddish-brown hardwood, among the heaviest in the Cameroonian forest. It is strong and reasonably durable, and is promoted for heavy construction, sleepers, piling and industrial flooring. Sawing and machining are difficult and all fixings must be pre-bored.',
                'characteristics' => ['Colour' => 'Reddish brown', 'Grain' => 'Interlocked', 'Texture' => 'Medium to coarse', 'Working' => 'Extremely hard — pre-bore all fixings'],
                'density_kg_m3_min' => 900, 'density_kg_m3_max' => 1100,
                'durability_class' => 'Class 2–3 (Durable to Moderately Durable)', 'janka_hardness' => 12000,
                'typical_uses' => ['Heavy construction and piling', 'Railway sleepers', 'Industrial flooring', 'Bridge components'],
                'commercial_category' => $promoted, 'is_promoted' => true,
                'region_availability' => ['East', 'South', 'Centre'],
            ],
            [
                'slug' => 'angueuk',
                'common_name' => 'Angueuk',
                'scientific_name' => 'Ongokea gore',
                'family' => 'Aptandraceae',
                'trade_names' => ['Angueuk', 'Boleko', 'Isano', 'Ongokea'],
                'local_names' => ['Angueuk', 'Boleko'],
                'description' => 'Angueuk is a dense yellow-brown hardwood with a fine texture, best known outside the timber trade as the source of isano oil from its seeds. As a timber it is hard, reasonably durable and promoted for flooring, joinery and turnery. It is heavy to work and dries slowly.',
                'characteristics' => ['Colour' => 'Yellow-brown', 'Grain' => 'Straight to interlocked', 'Texture' => 'Fine', 'Drying' => 'Slow'],
                'density_kg_m3_min' => 800, 'density_kg_m3_max' => 950,
                'durability_class' => 'Class 2 (Durable)', 'janka_hardness' => 8500,
                'typical_uses' => ['Flooring', 'Joinery', 'Turnery', 'Heavy interior work'],
                'commercial_category' => $promoted, 'is_promoted' => true,
                'region_availability' => ['East', 'South', 'Centre'],
            ],
            [
                'slug' => 'essessang',
                'common_name' => 'Essessang',
                'scientific_name' => 'Ricinodendron heudelotii',
                'family' => 'Euphorbiaceae',
                'trade_names' => ['Essessang', 'Erimado', 'Munguella', 'African nut tree'],
                'local_names' => ['Njangsang', 'Essessang'],
                'description' => 'Essessang is a very light, pale creamy-white wood — one of the lightest commercial timbers of the region — used for floats, model making, packaging and light plywood core. The tree is far better known locally for njangsang, the spice made from its seeds. The wood has no natural durability and must be protected in any exposed use.',
                'characteristics' => ['Colour' => 'Creamy white to pale yellow', 'Grain' => 'Straight', 'Texture' => 'Coarse', 'Weight' => 'Very light — among the lightest African timbers'],
                'density_kg_m3_min' => 200, 'density_kg_m3_max' => 350,
                'durability_class' => 'Class 5 (Not Durable)', 'janka_hardness' => 1500,
                'typical_uses' => ['Floats and buoyancy blocks', 'Model making', 'Packaging and crating', 'Plywood core', 'Insulation panels'],
                'commercial_category' => $promoted, 'is_promoted' => true,
                'region_availability' => ['Centre', 'East', 'South', 'South-West', 'Littoral'],
            ],
            [
                'slug' => 'fromager',
                'common_name' => 'Fromager',
                'scientific_name' => 'Ceiba pentandra',
                'family' => 'Malvaceae',
                'trade_names' => ['Ceiba', 'Kapok', 'Fuma', 'Bombax'],
                'local_names' => ['Doum', 'Fromager'],
                'description' => 'Fromager, the kapok or silk-cotton tree, yields a very light whitish wood that peels easily and is used mainly for plywood core, packaging and light interior work. It has essentially no natural durability and is highly susceptible to fungal and insect attack, so it must be converted and treated promptly. Its lightness and availability make it a staple utility timber.',
                'characteristics' => ['Colour' => 'Whitish to pale yellow-brown', 'Grain' => 'Interlocked', 'Texture' => 'Coarse', 'Note' => 'Very perishable — treat immediately after conversion'],
                'density_kg_m3_min' => 230, 'density_kg_m3_max' => 400,
                'durability_class' => 'Class 5 (Not Durable)', 'janka_hardness' => 1300,
                'typical_uses' => ['Plywood core and blockboard', 'Packaging and crating', 'Light interior work', 'Model making', 'Dugout canoes'],
                'commercial_category' => $softwood, 'is_promoted' => false,
                'region_availability' => ['Centre', 'Littoral', 'South', 'South-West', 'East'],
            ],
            [
                'slug' => 'emien',
                'common_name' => 'Emien',
                'scientific_name' => 'Alstonia boonei',
                'family' => 'Apocynaceae',
                'trade_names' => ['Emien', 'Stoolwood', 'Alstonia', 'Ekouk'],
                'local_names' => ['Ekouk', 'Emien'],
                'description' => 'Emien is a pale creamy-white, low-density wood with a straight grain and a fine even texture that carves and machines very easily. It is used for pattern making, carving, light joinery, plywood core and packaging. It has no natural durability and stains readily, so prompt conversion and treatment are needed.',
                'characteristics' => ['Colour' => 'Creamy white to pale yellow', 'Grain' => 'Straight', 'Texture' => 'Fine and even', 'Working' => 'Very easy to carve and machine'],
                'density_kg_m3_min' => 320, 'density_kg_m3_max' => 450,
                'durability_class' => 'Class 5 (Not Durable)', 'janka_hardness' => 1600,
                'typical_uses' => ['Carving and pattern making', 'Light joinery', 'Plywood core', 'Packaging', 'Mouldings'],
                'commercial_category' => $softwood, 'is_promoted' => false,
                'region_availability' => ['Centre', 'South', 'Littoral', 'South-West', 'East'],
            ],
        ];
    }
}
