<?php

namespace Database\Factories;

use App\Enums\CompanyStatus;
use App\Models\Company;
use App\Models\CompanyContact;
use App\Models\Species;
use App\Models\VerificationBadge;
use Illuminate\Database\Eloquent\Factories\Factory;

/** @extends Factory<Company> */
class CompanyFactory extends Factory
{
    protected $model = Company::class;

    public function definition(): array
    {
        return [
            // slug auto-generated by HasSlug from the name accessor when blank.
            'legal_name' => $this->faker->company().' Sarl',
            'trade_name' => null,
            'status' => CompanyStatus::Draft,
            'description' => $this->faker->paragraphs(2, true),
            'region' => $this->faker->randomElement(['Centre', 'Littoral', 'South', 'East', 'South-West']),
            'city' => $this->faker->city(),
            'country_code' => 'CM',
            'email' => $this->faker->companyEmail(),
            'phone' => $this->faker->numerify('+237 6########'),
        ];
    }

    /** Verified status + logo present (two of the visibility requirements). */
    public function verified(): static
    {
        return $this->state(fn () => [
            'status' => CompanyStatus::Verified,
            'verified_at' => now(),
            'logo_path' => 'companies/demo/logo.png',
        ]);
    }

    /** Satisfies every Company::scopePubliclyVisible() predicate. */
    public function publiclyVisible(): static
    {
        return $this->verified()->afterCreating(function (Company $company): void {
            CompanyContact::factory()->create(['company_id' => $company->id, 'is_public' => true]);
            $species = Species::factory()->create();
            $company->species()->attach($species);
            VerificationBadge::factory()->create(['company_id' => $company->id]);
        });
    }

    public function status(CompanyStatus $status): static
    {
        return $this->state(['status' => $status]);
    }
}
