<?php

namespace Database\Factories;

use App\Enums\PriceUnit;
use App\Enums\ProductStatus;
use App\Enums\ProductType;
use App\Models\Category;
use App\Models\Company;
use App\Models\Product;
use App\Models\Species;
use App\Support\CategoryMigrationMap;
use Illuminate\Database\Eloquent\Factories\Factory;

/** @extends Factory<Product> */
class ProductFactory extends Factory
{
    protected $model = Product::class;

    public function definition(): array
    {
        $productType = $this->faker->randomElement(ProductType::cases());

        return [
            // slug auto-generated by HasSlug from name when left blank.
            'company_id' => Company::factory(),
            'species_id' => Species::factory(),
            'name' => ucfirst($this->faker->unique()->words(2, true)).' Sawn Timber',
            'product_type' => $productType,
            // Keep category_id consistent with product_type (the domestic
            // marketplace facets on the Category tree — gap-plan 1.5.2b).
            // A default, so `->create(['category_id' => null])` still overrides
            // it to null when a test wants the no-category path.
            'category_id' => fn (array $attrs): ?int => Category::query()
                ->where('kind', 'form')
                ->where('slug', CategoryMigrationMap::MAP[
                    ($attrs['product_type'] ?? $productType) instanceof ProductType
                        ? ($attrs['product_type'] ?? $productType)->value
                        : ($attrs['product_type'] ?? $productType)
                ] ?? '__none__')
                ->value('id'),
            'description' => $this->faker->paragraph(),
            'price_amount' => $this->faker->numberBetween(200, 900) * 1000,
            'price_currency' => 'XAF',
            'price_unit' => PriceUnit::CubicMetre,
            'moq_quantity' => 20,
            'moq_unit' => PriceUnit::CubicMetre,
            'grade' => 'Select & Better',
            'thickness_mm' => 50,
            'width_min_mm' => 100,
            'width_max_mm' => 250,
            'length_min_m' => 2.4,
            'length_max_m' => 6.0,
            'moisture_content' => '12% - 15% (KD)',
            'origin' => 'Cameroon',
            'certification' => 'Legal Origin Verified',
            'status' => ProductStatus::Draft,
            'is_featured' => false,
            'is_best_seller' => false,
            'reviews_count' => 0,
            'buyers_count' => 0,
        ];
    }

    public function draft(): static
    {
        return $this->state(['status' => ProductStatus::Draft]);
    }

    public function active(): static
    {
        return $this->state(['status' => ProductStatus::Active]);
    }

    public function archived(): static
    {
        return $this->state(['status' => ProductStatus::Archived]);
    }

    public function featured(): static
    {
        return $this->state(['status' => ProductStatus::Active, 'is_featured' => true]);
    }
}
