<?php

namespace Database\Factories;

use App\Models\Species;
use Illuminate\Database\Eloquent\Factories\Factory;

/** @extends Factory<Species> */
class SpeciesFactory extends Factory
{
    protected $model = Species::class;

    public function definition(): array
    {
        return [
            // slug auto-generated by HasSlug from common_name when left blank.
            'common_name' => ucfirst($this->faker->unique()->word()),
            'scientific_name' => ucfirst($this->faker->word()).' '.$this->faker->word(),
            'description' => $this->faker->paragraph(),
            'is_cites_listed' => false,
            'is_published' => true,
            'sort_order' => 0,
        ];
    }

    public function unpublished(): static
    {
        return $this->state(['is_published' => false]);
    }
}
