/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1.auth.register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * The failure message is deliberately one generic string on the `email`
         *     field for every cause — unknown address, wrong password, anything else.
         *     Distinguishing them would turn this endpoint into an account-existence
         *     oracle. The password check runs even when no user matched, so the
         *     response time does not leak the answer either
         */
        post: operations["v1.auth.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revokes only the token that made this call — other devices stay signed in */
        post: operations["v1.auth.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1.auth.me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderReference}/disputes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1.orders.disputes.index"];
        put?: never;
        post: operations["v1.orders.disputes.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderReference}/disputes/{dispute}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1.orders.disputes.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderReference}/disputes/{dispute}/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1.orders.disputes.reply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1.orders.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1.orders.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{reference}/shipments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The order's shipment(s) plus each one's checkpoint history — a natural
         *     companion to `show()`/`trade-assurance` (blueprint §45-46 wiring
         *     exposed to the buyer app). Goes through GetOrderShipmentTrackingQuery
         *     via QueryBus, which itself enforces ownership through the same
         *     BuyerApiScope::order() boundary `show()` uses: another buyer's
         *     reference 404s here too. An order with no linked shipment yet returns
         *     an empty `data` array, not an error
         */
        get: operations["v1.orders.shipments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1.products.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1.products.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quotes/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1.quotes.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quotes/{reference}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1.quotes.accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quotes/{reference}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1.quotes.decline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rfqs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1.rfqs.index"];
        put?: never;
        post: operations["v1.rfqs.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rfqs/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1.rfqs.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rfqs/{reference}/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-send the signed 48-hour verification link for one of the buyer's own
         *     RFQs
         * @description Scoped through BuyerApiScope, so another buyer's reference 404s rather
         *     than 403s — the endpoint leaks no more than `show()` does. An RFQ that is
         *     already verified is a no-op 200, not an error: the client asking twice is
         *     a retry, not a fault, and answering 409 would only teach it to guess.
         *
         *     This mints a fresh link through the same IntakeService helper
         *     `createRfq()` uses; it does not verify anything itself.
         */
        post: operations["v1.rfqs.resend-verification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rfqs/{reference}/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quotes suppliers have returned on one of the buyer's own RFQs */
        get: operations["v1.rfqs.quotes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1.search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/species": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1.species.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/species/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1.species.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1.suppliers.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suppliers/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1.suppliers.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderReference}/trade-assurance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1.orders.trade-assurance.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderReference}/trade-assurance/milestones/{milestoneId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1.orders.trade-assurance.confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * DeclineQuoteRequest
         * @description Declining is a recorded decision the supplier reads, so a reason is
         *     mandatory — QuoteService::decline() throws on an empty one, and this turns
         *     that into a 422 with a field-level message instead of a 500.
         */
        DeclineQuoteRequest: {
            reason: string;
        };
        /** DisputeEvidenceResource */
        DisputeEvidenceResource: {
            id: number;
            description: string;
            has_file: boolean;
            original_filename?: string | null;
            submitted_by_user_name?: string;
            submitted_by_company_name?: string | null;
            created_at: string | null;
        };
        /** DisputeMessageResource */
        DisputeMessageResource: {
            id: number;
            body: string;
            user_name?: string;
            company_name?: string | null;
            created_at: string | null;
        };
        /** DisputeResource */
        DisputeResource: {
            id: number;
            order_id: number;
            category: string;
            /** @enum {string} */
            category_label: "Quality" | "Quantity" | "Delay" | "Payment" | "Other";
            status: string;
            /** @enum {string} */
            status_label: "Opened" | "Evidence submission" | "Counterparty response" | "Under review" | "Resolved" | "Appealed" | "Closed";
            description: string;
            raised_by_user_name?: string;
            raised_by_company_name?: string | null;
            respondent_company_name?: string | null;
            resolution_notes: string | null;
            resolved_at: string | null;
            appealed_at: string | null;
            closed_at: string | null;
            created_at: string | null;
            evidence?: components["schemas"]["DisputeEvidenceResource"][];
            messages?: components["schemas"]["DisputeMessageResource"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
            /**
             * @description Names the device the token belongs to, so a buyer can tell one
             *     handset from another when tokens are listed or revoked.
             */
            device_name?: string | null;
        };
        /**
         * OpenDisputeRequest
         * @description Payload to open a new dispute on an order — mirrors
         *     `Public\DisputeController::store()`'s own validation exactly, so the API
         *     and web forms accept/reject the same input.
         */
        OpenDisputeRequest: {
            /** @enum {string} */
            category: "quality" | "quantity" | "delay" | "payment" | "other";
            description: string;
        };
        /** OrderItemResource */
        OrderItemResource: {
            id: number;
            description: string;
            species_name: string | null;
            form: string | null;
            grade: string | null;
            dimensions: string | null;
            quantity: string;
            unit: string;
            unit_price: string;
            line_total: string;
        };
        /** OrderResource */
        OrderResource: {
            reference: string;
            status: string;
            /** @enum {string} */
            status_label: "Awarded" | "Confirmed" | "In production" | "Shipped" | "Delivered" | "Completed" | "Cancelled";
            payment_status: string;
            currency: string;
            subtotal_amount: string;
            shipping_amount: string | null;
            tax_amount: string | null;
            total_amount: string;
            incoterm: string | null;
            payment_terms: string | null;
            lead_time_days: number | null;
            shipping_port: string | null;
            destination_country_code: string | null;
            expected_delivery_at: string | null;
            etd: string | null;
            eta: string | null;
            supplier_name: string;
            awarded_at: string | null;
            confirmed_at: string | null;
            production_started_at: string | null;
            shipped_at: string | null;
            delivered_at: string | null;
            completed_at: string | null;
            cancelled_at: string | null;
            created_at: string | null;
            items?: components["schemas"]["OrderItemResource"][];
            has_trade_assurance: boolean | null;
        };
        /** OrderSummaryResource */
        OrderSummaryResource: {
            reference: string;
            status: string;
            /** @enum {string} */
            status_label: "Awarded" | "Confirmed" | "In production" | "Shipped" | "Delivered" | "Completed" | "Cancelled";
            currency: string;
            total_amount: string;
            supplier_name: string;
            awarded_at: string | null;
            created_at: string | null;
        };
        /** ProductDetailResource */
        ProductDetailResource: {
            id: number;
            slug: string;
            name: string;
            product_type: string;
            /** @enum {string} */
            product_type_label: "Sawn Timber" | "Logs" | "Veneer" | "Flooring" | "Decking" | "Mouldings" | "Plywood" | "Beams" | "Planks" | "Boules / Through-and-through" | "Squares / Scantlings" | "Railway Sleepers" | "Poles & Posts" | "Live-edge Slabs" | "Laminated / Edge-glued Panels" | "Charcoal & Biomass";
            grade: string | null;
            origin: string;
            certification: string | null;
            price: {
                amount: string | null;
                currency: string;
                currency_label: string;
                unit: string;
                /** @enum {string} */
                unit_label: "m³" | "m²" | "pcs" | "ton";
                label: string | null;
                indicative_usd: string | null;
            };
            moq: {
                quantity: string | null;
                unit: string;
                label: string | null;
            };
            is_featured: boolean;
            is_best_seller: boolean;
            rating: {
                average: number;
                count: number;
            } | null;
            primary_image_url: string | null;
            created_at: string | null;
            species?: {
                slug: string;
                common_name: string;
            } | null;
            supplier?: components["schemas"]["SupplierDetailResource"] & Record<string, never>;
            tagline: string | null;
            description: string | null;
            key_benefits: unknown[] | null;
            width: string | null;
            length: string | null;
            thickness_mm: string | null;
            moisture_content: string | null;
            specifications: {
                label: string;
                value: string;
            }[];
            trust_badges: {
                key: string;
                label: string;
                icon: string;
            }[];
            gallery: {
                url: string;
                alt: string;
            }[];
            species_detail: components["schemas"]["SpeciesDetailResource"] | null;
        };
        /** ProductResource */
        ProductResource: {
            id: number;
            slug: string;
            name: string;
            product_type: string;
            /** @enum {string} */
            product_type_label: "Sawn Timber" | "Logs" | "Veneer" | "Flooring" | "Decking" | "Mouldings" | "Plywood" | "Beams" | "Planks" | "Boules / Through-and-through" | "Squares / Scantlings" | "Railway Sleepers" | "Poles & Posts" | "Live-edge Slabs" | "Laminated / Edge-glued Panels" | "Charcoal & Biomass";
            grade: string | null;
            origin: string;
            certification: string | null;
            price: {
                amount: string | null;
                currency: string;
                currency_label: string;
                unit: string;
                /** @enum {string} */
                unit_label: "m³" | "m²" | "pcs" | "ton";
                label: string | null;
                indicative_usd: string | null;
            };
            moq: {
                quantity: string | null;
                unit: string;
                label: string | null;
            };
            is_featured: boolean;
            is_best_seller: boolean;
            rating: {
                average: number;
                count: number;
            } | null;
            primary_image_url: string | null;
            created_at: string | null;
            species?: {
                slug: string;
                common_name: string;
            } | null;
            supplier?: components["schemas"]["SupplierResource"];
        };
        /** QuoteItemResource */
        QuoteItemResource: {
            id: number;
            description: string;
            form: components["schemas"]["TimberForm"] | null;
            grade: string | null;
            dimensions: string | null;
            quantity: string;
            unit: components["schemas"]["RfqUnit"];
            unit_price: string;
            line_total: string;
        };
        /** QuoteResource */
        QuoteResource: {
            reference: string;
            status: string;
            /** @enum {string} */
            status_label: "Draft" | "Submitted" | "Viewed" | "Accepted" | "Declined" | "Withdrawn" | "Expired";
            currency: string;
            incoterm: string | null;
            subtotal_amount: string;
            shipping_amount: string | null;
            tax_amount: string | null;
            total_amount: string;
            lead_time_days: number | null;
            validity_days: number | null;
            valid_until: string | null;
            payment_terms: string | null;
            notes: string | null;
            submitted_at: string | null;
            decided_at: string | null;
            decline_reason: string | null;
            is_expired: boolean;
            is_actionable: boolean;
            rfq_reference?: string;
            supplier?: components["schemas"]["SupplierResource"];
            items?: components["schemas"]["QuoteItemResource"][];
        };
        /**
         * RegisterRequest
         * @description Registration rules come straight from RegisterAccount, the shared action the
         *     web form uses, so the two paths can never drift apart.
         */
        RegisterRequest: {
            /** @enum {string} */
            account_type: "buyer" | "supplier" | "processor" | "artisan" | "carbon_developer" | "carbon_buyer" | "logistics_partner";
            name: string;
            /** Format: email */
            email: string;
            company_name: string;
            company_phone?: string | null;
            company_city?: string | null;
            company_country?: string | null;
            company_registration_number?: string | null;
            password: string;
        };
        /**
         * ReplyDisputeRequest
         * @description Payload for a threaded reply on a dispute — mirrors
         *     `Public\DisputeController::reply()`'s own validation exactly. Evidence
         *     upload (with a file) stays web-only for this pass; see
         *     `DisputeController@reply`'s docblock in Api/V1 for why.
         */
        ReplyDisputeRequest: {
            body: string;
        };
        /** RfqItemResource */
        RfqItemResource: {
            id: number;
            species_text: string | null;
            form: components["schemas"]["TimberForm"] | null;
            grade: string | null;
            dimensions: string | null;
            moisture_content: string | null;
            quantity: string | null;
            unit: string | null;
            species?: {
                slug: string;
                common_name: string;
            } | null;
        };
        /** RfqResource */
        RfqResource: {
            reference: string;
            title: string | null;
            project_name: string | null;
            status: string;
            /** @enum {string} */
            status_label: "New" | "In review" | "Approved" | "Rejected" | "Spam" | "Closed";
            email_verified: boolean;
            email_verified_at: string | null;
            /**
             * @description An unverified RFQ is not routed to suppliers until the buyer
             *     opens the emailed signed link, so the client has to be able to
             *     render "check your email" and offer a resend from ANY payload —
             *     not only from the 201 that created it. Previously the state was
             *     only legible in the create response's `meta`, which left a client
             *     that reloaded its list with no way to explain a stalled RFQ.
             */
            verification: {
                required: boolean;
                verified: boolean;
                verified_at: string | null;
                resend_path: string | null;
            };
            buyer_name: string;
            buyer_company: string | null;
            buyer_email: string;
            buyer_country_code: string | null;
            destination_country_code: string | null;
            incoterm: string | null;
            shipping_port: string | null;
            target_amount: string | null;
            target_currency: string | null;
            deadline: string | null;
            notes: string | null;
            created_at: string | null;
            items?: components["schemas"]["RfqItemResource"][];
            quotes_count?: number;
        };
        /**
         * RfqUnit
         * @description Quantity unit an RFQ line item is expressed in. Mirrors the `rfq_items_unit_check` CHECK constraint exactly — the database is the source of truth, this enum is how the app reads it.
         * @enum {string}
         */
        RfqUnit: "m3" | "ton" | "pcs" | "container";
        /** ShipmentTrackingResource */
        ShipmentTrackingResource: {
            waybill_number: string;
            /** @enum {string|null} */
            current_status: "Dispatched" | "In transit" | "Delayed" | "Delivered" | null;
            current_status_updated_at: string | null;
            checkpoints: string[] | string[];
        };
        /** SpeciesDetailResource */
        SpeciesDetailResource: {
            id: number;
            slug: string;
            common_name: string;
            scientific_name: string | null;
            family: string | null;
            trade_names: unknown[] | null;
            commercial_category: string | null;
            /** @enum {string|null} */
            commercial_category_label: "Primary / Principal Hardwood" | "Promoted Species — Essence de Promotion" | "Secondary Hardwood" | "Softwood" | "Specialty / Precious Wood" | null;
            is_cites_listed: boolean;
            is_promoted: boolean;
            log_export_status: string | null;
            /** @enum {string|null} */
            log_export_status_label: "Permitted" | "Restricted" | "Banned" | "Unknown / not verified" | null;
            /** @constant */
            log_export_status_note: "Informational only — verify against current MINFOF publications.";
            density_kg_m3_min: number | null;
            density_kg_m3_max: number | null;
            density_range: string | null;
            durability_class: string | null;
            janka_hardness: number | null;
            is_premium: boolean;
            products_count?: number;
            description: string | null;
            local_names: unknown[] | null;
            characteristics: unknown[] | null;
            typical_uses: unknown[] | null;
            region_availability: unknown[] | null;
            swatch: {
                image: string | null;
                from: string;
                via: string;
                to: string;
            };
        };
        /** SpeciesResource */
        SpeciesResource: {
            id: number;
            slug: string;
            common_name: string;
            scientific_name: string | null;
            family: string | null;
            trade_names: unknown[] | null;
            commercial_category: string | null;
            /** @enum {string|null} */
            commercial_category_label: "Primary / Principal Hardwood" | "Promoted Species — Essence de Promotion" | "Secondary Hardwood" | "Softwood" | "Specialty / Precious Wood" | null;
            is_cites_listed: boolean;
            is_promoted: boolean;
            log_export_status: string | null;
            /** @enum {string|null} */
            log_export_status_label: "Permitted" | "Restricted" | "Banned" | "Unknown / not verified" | null;
            /** @constant */
            log_export_status_note: "Informational only — verify against current MINFOF publications.";
            density_kg_m3_min: number | null;
            density_kg_m3_max: number | null;
            density_range: string | null;
            durability_class: string | null;
            janka_hardness: number | null;
            is_premium: boolean;
            products_count?: number;
        };
        /**
         * StoreRfqRequest
         * @description RFQ creation payload for the mobile client.
         *
         *     The rules are RfqWizard's own — the whole wizard's rule set, flattened —
         *     minus the two browser-form artefacts: the `consent` checkbox (the native
         *     client presents its own consent copy) and the contact *identity* block, which
         *     the API takes from the authenticated account rather than from the request
         *     body. A buyer cannot raise an RFQ under someone else's name or address
         *     through this endpoint, because those fields are not accepted at all.
         *
         *     `buyer_company` is the exception and deliberately so: it is descriptive, not
         *     identifying — the organisation the buyer is purchasing for, which the web
         *     wizard collects on the contact step and stores in `rfqs.buyer_company`.
         *     Accepting it here matches the web; dropping it silently, as this request used
         *     to, was the worst of the three options.
         *
         *     Species on a line item may be given three ways, in this order of precedence:
         *
         *       - `species_slug` — the catalogue slug the client actually holds, since the
         *         `/species` endpoints are keyed by slug and never expose numeric ids.
         *         Resolved here against PUBLISHED species only; an unknown or unpublished
         *         slug is a 422 on `items.N.species_slug`, never a silently null link.
         *       - `species_id` — kept working for callers that already have an id.
         *       - `species_text` — free text, for timber that is legitimately not in the
         *         catalogue. Still required when neither of the above is given.
         */
        StoreRfqRequest: {
            title: string;
            project_name?: string | null;
            /** Format: date-time */
            deadline?: string | null;
            items: {
                species_id?: number | null;
                species_text?: string | null;
                /** @enum {string} */
                form: "logs" | "sawn" | "veneer" | "plywood" | "other";
                grade?: string | null;
                dimensions?: string | null;
                quantity: number;
                /** @enum {string} */
                unit: "m3" | "ton" | "pcs" | "container";
                moisture_content?: string | null;
                species_slug?: string | null;
            }[];
            destination_country_code: string;
            shipping_port?: string | null;
            /** @enum {string|null} */
            incoterm?: "EXW" | "FOB" | "CFR" | "CIF" | "DAP" | null;
            target_amount?: number | null;
            /** @enum {string|null} */
            target_currency?: "XAF" | "USD" | "EUR" | "GBP" | "CNY" | null;
            notes: string;
            buyer_company?: string | null;
            buyer_country_code: string;
            website?: string | null;
            form_rendered_at?: number | null;
        };
        /** SupplierDetailResource */
        SupplierDetailResource: {
            id: number;
            slug: string;
            name: string;
            legal_name: string;
            trade_name: string | null;
            city: string | null;
            region: string | null;
            country_code: string;
            logo_url: string;
            supplier_type: string | null;
            is_featured: boolean;
            verified_at: string | null;
            years_experience: number | null;
            response_rate_percent: number | null;
            orders_completed: number | null;
            rating: {
                average: number;
                count: number;
            } | null;
            products_count?: number;
            species?: string[];
            description: string | null;
            website_url: string | null;
            languages: unknown[] | null;
            annual_capacity_m3: string | null;
            delivery_time: string | null;
            response_time: string | null;
            member_since: string | null;
            export_markets?: unknown[];
            badges?: string;
            contacts?: string[];
        };
        /** SupplierResource */
        SupplierResource: {
            id: number;
            slug: string;
            name: string;
            legal_name: string;
            trade_name: string | null;
            city: string | null;
            region: string | null;
            country_code: string;
            logo_url: string;
            supplier_type: string | null;
            is_featured: boolean;
            verified_at: string | null;
            years_experience: number | null;
            response_rate_percent: number | null;
            orders_completed: number | null;
            rating: {
                average: number;
                count: number;
            } | null;
            products_count?: number;
            species?: string[];
        };
        /**
         * TimberForm
         * @description Form (processing state) of a timber product: used in RFQ line items and on company-species records to describe what a company can supply.
         * @enum {string}
         */
        TimberForm: "logs" | "sawn" | "veneer" | "plywood" | "other";
        /** TradeAssuranceMilestoneResource */
        TradeAssuranceMilestoneResource: {
            id: number;
            sequence: number;
            title: string;
            description: string | null;
            status: string;
            /** @enum {string} */
            status_label: "Pending" | "In progress" | "Buyer confirmed" | "Disputed" | "Released";
            amount_share_percent: string | null;
            expected_completion_date: string | null;
            confirmed_at: string | null;
            can_confirm: boolean;
        };
        /** TradeAssuranceResource */
        TradeAssuranceResource: {
            id: number;
            order_reference: string;
            milestones?: components["schemas"]["TradeAssuranceMilestoneResource"][];
            created_at: string | null;
        };
        /** UserResource */
        UserResource: {
            id: number;
            name: string;
            email: string;
            email_verified: boolean;
            email_verified_at: string | null;
            created_at: string | null;
        };
    };
    responses: {
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
        /** @description Unauthenticated */
        AuthenticationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Authorization error */
        AuthorizationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Not found */
        ModelNotFoundException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "v1.auth.register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            token: string;
                            user: components["schemas"]["UserResource"];
                        };
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "v1.auth.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            token: string;
                            user: components["schemas"]["UserResource"];
                        };
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "v1.auth.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "v1.auth.me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `UserResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "v1.orders.disputes.index": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderReference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `DisputeResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DisputeResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "v1.orders.disputes.store": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderReference: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenDisputeRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Dispute opened.";
                        data: components["schemas"]["DisputeResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "v1.orders.disputes.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderReference: string;
                dispute: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DisputeResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            /** @description An error */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error overview.
                         * @example
                         */
                        message: string;
                    };
                };
            };
        };
    };
    "v1.orders.disputes.reply": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderReference: string;
                dispute: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplyDisputeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Response sent.";
                        data: components["schemas"]["DisputeResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "v1.orders.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `OrderResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OrderResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "v1.orders.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `OrderResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OrderResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "v1.orders.shipments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `ShipmentTrackingResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ShipmentTrackingResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "v1.products.index": {
        parameters: {
            query?: {
                q?: string | null;
                "types[]"?: "sawn_timber" | "logs" | "veneer" | "flooring" | "decking" | "mouldings" | "plywood" | "beams" | "planks" | "boules" | "squares" | "sleepers" | "poles" | "slabs" | "laminated_panels" | "charcoal";
                "species[]"?: string[];
                region?: string | null;
                supplier?: string | null;
                certified?: boolean | null;
                best_sellers?: boolean | null;
                sort?: "featured" | "price_low" | "price_high" | "newest" | "name" | null;
                per_page?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `ProductResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProductResource"][];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                            facets: {
                                types: {
                                    value: string;
                                    /** @enum {string} */
                                    label: "Sawn Timber" | "Logs" | "Veneer" | "Flooring" | "Decking" | "Mouldings" | "Plywood" | "Beams" | "Planks" | "Boules / Through-and-through" | "Squares / Scantlings" | "Railway Sleepers" | "Poles & Posts" | "Live-edge Slabs" | "Laminated / Edge-glued Panels" | "Charcoal & Biomass";
                                    count: number;
                                }[];
                                species: string[];
                                regions: string[];
                                flags: number[];
                            };
                            sort_options: {
                                /** @constant */
                                featured: "Featured";
                                /** @constant */
                                price_low: "Price (low to high)";
                                /** @constant */
                                price_high: "Price (high to low)";
                                /** @constant */
                                newest: "Newest listings";
                                /** @constant */
                                name: "Name (A–Z)";
                            };
                        };
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "v1.products.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `ProductDetailResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProductDetailResource"] & Record<string, never>;
                    };
                };
            };
        };
    };
    "v1.quotes.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `QuoteResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["QuoteResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "v1.quotes.accept": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            quote: components["schemas"]["QuoteResource"] & Record<string, never>;
                            order: components["schemas"]["OrderSummaryResource"] | null;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    "v1.quotes.decline": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeclineQuoteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["QuoteResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "v1.rfqs.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `RfqResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: (components["schemas"]["RfqResource"] & Record<string, never>)[];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "v1.rfqs.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreRfqRequest"];
            };
        };
        responses: {
            /** @description `RfqResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RfqResource"] & Record<string, never>;
                        meta: {
                            email_verification_required: boolean;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "v1.rfqs.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `RfqResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RfqResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "v1.rfqs.resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        message: "This request is already verified." | "We have re-sent the confirmation email.";
                        data: {
                            reference: string;
                            email_verified: boolean;
                            email_verification_required: boolean;
                            sent: boolean;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "v1.rfqs.quotes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `QuoteResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["QuoteResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "v1.search": {
        parameters: {
            query?: {
                q?: string | null;
                type?: "products" | "suppliers" | "species" | null;
                species?: string | null;
                product_type?: "sawn_timber" | "logs" | "veneer" | "flooring" | "decking" | "mouldings" | "plywood" | "beams" | "planks" | "boules" | "squares" | "sleepers" | "poles" | "slabs" | "laminated_panels" | "charcoal" | null;
                grade?: string | null;
                country?: string | null;
                sort?: "relevance" | "price_asc" | "price_desc" | "newest" | null;
                per_page?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: string[];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "v1.species.index": {
        parameters: {
            query?: {
                q?: string | null;
                "categories[]"?: "primary_hardwood" | "promoted_species" | "secondary_hardwood" | "softwood" | "specialty";
                "properties[]"?: "durable" | "insect-resistant" | "water-resistant" | "easy-to-work" | "decorative" | "lightweight";
                "applications[]"?: "furniture" | "flooring" | "construction" | "joinery" | "boat-building" | "veneer" | "decking" | "musical";
                region?: string | null;
                in_stock?: boolean | null;
                sort?: "popularity" | "name" | "density" | "durability" | null;
                per_page?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `SpeciesResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SpeciesResource"][];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                            facets: {
                                categories: {
                                    value: string;
                                    /** @enum {string} */
                                    label: "Primary hardwood" | "Promoted species" | "Secondary hardwood" | "Softwood" | "Specialty wood";
                                    count: number;
                                }[];
                                properties: {
                                    value: string;
                                    label: string;
                                    count: number;
                                }[];
                                applications: {
                                    value: string;
                                    label: string;
                                    count: number;
                                }[];
                                regions: {
                                    value: string;
                                    count: number;
                                }[];
                                in_stock: {
                                    /** @constant */
                                    value: "1";
                                    /** @constant */
                                    label: "In Stock";
                                    count: number;
                                } | null;
                            };
                            sort_options: {
                                /** @constant */
                                popularity: "Popularity";
                                /** @constant */
                                name: "Name (A–Z)";
                                /** @constant */
                                density: "Density (heaviest)";
                                /** @constant */
                                durability: "Durability";
                            };
                        };
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "v1.species.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `SpeciesDetailResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SpeciesDetailResource"];
                    };
                };
            };
        };
    };
    "v1.suppliers.index": {
        parameters: {
            query?: {
                q?: string | null;
                region?: string | null;
                species?: string | null;
                market?: string | null;
                "types[]"?: "manufacturer" | "exporter" | "trader" | "service_provider" | "logistics_provider";
                "specs[]"?: "sawn_timber" | "logs" | "veneer" | "flooring" | "decking" | "mouldings" | "plywood" | "beams" | "planks" | "boules" | "squares" | "sleepers" | "poles" | "slabs" | "laminated_panels" | "charcoal";
                min_years?: number | null;
                sort?: "featured" | "name" | "newest" | "response" | "experience" | null;
                per_page?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `SupplierResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SupplierResource"][];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                            sort_options: {
                                /** @constant */
                                featured: "Featured";
                                /** @constant */
                                name: "Name (A–Z)";
                                /** @constant */
                                newest: "Recently verified";
                                /** @constant */
                                response: "Response rate";
                                /** @constant */
                                experience: "Experience";
                            };
                        };
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "v1.suppliers.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `SupplierDetailResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SupplierDetailResource"] & Record<string, never>;
                    };
                };
            };
        };
    };
    "v1.orders.trade-assurance.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderReference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TradeAssuranceResource"] & Record<string, never>;
                    } | {
                        data: null;
                        /** @constant */
                        message: "A Trade Assurance agreement has not been set up for this order.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "v1.orders.trade-assurance.confirm": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderReference: string;
                milestoneId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Milestone confirmed.";
                        data: components["schemas"]["TradeAssuranceResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
}
