@php $data = $wizard->step('details'); @endphp

<fieldset class="space-y-5">
    <legend class="sr-only">RFQ details</legend>

    <div class="grid gap-5 sm:grid-cols-2">
        <x-rfq.field name="title" label="RFQ title" required class="sm:col-span-2"
                     :value="$data['title'] ?? null"
                     :autofocus="$errors->has('title') || ! $errors->any()"
                     placeholder="e.g. Sapele sawn timber for Q3 joinery"
                     help="A short headline our team and the exporters will see first."
                     maxlength="160" />

        <x-rfq.field name="project_name" label="Project name"
                     :value="$data['project_name'] ?? null"
                     :autofocus="$errors->has('project_name')"
                     placeholder="e.g. Douala port terminal fit-out"
                     maxlength="160" />

        <x-rfq.field name="deadline" label="Response deadline" type="date"
                     :value="$data['deadline'] ?? null"
                     :autofocus="$errors->has('deadline')"
                     :min="now()->toDateString()"
                     help="The date by which you need quotes back." />
    </div>

    {{-- Reference codes are generated by the platform on submit, so there is no
         field for one here — the buyer receives it on the confirmation screen. --}}
    <p class="rounded-xl bg-sand-100 px-4 py-3 text-[0.8125rem] text-ink-soft dark:bg-[#26241e] dark:text-[#b3ab9b]">
        <x-heroicon-m-information-circle class="mr-1 inline h-4 w-4 align-text-bottom" />
        Your RFQ reference is generated automatically when you submit, and is shown on the confirmation screen and in your email.
    </p>
</fieldset>
