@php $data = $wizard->step('details'); @endphp

<fieldset class="space-y-5">
    <legend class="sr-only">{{ __('messages.rfq_wizard.rfq_details_legend') }}</legend>

    <div class="grid gap-5 sm:grid-cols-2">
        <x-rfq.field name="title" :label="__('messages.rfq_wizard.rfq_title')" required class="sm:col-span-2"
                     :value="$data['title'] ?? null"
                     :autofocus="$errors->has('title') || ! $errors->any()"
                     :placeholder="__('messages.rfq_wizard.rfq_title_ph')"
                     :help="__('messages.rfq_wizard.rfq_title_help')"
                     maxlength="160" />

        <x-rfq.field name="project_name" :label="__('messages.rfq_wizard.project_name')"
                     :value="$data['project_name'] ?? null"
                     :autofocus="$errors->has('project_name')"
                     :placeholder="__('messages.rfq_wizard.project_name_ph')"
                     maxlength="160" />

        <x-rfq.field name="deadline" :label="__('messages.rfq_wizard.response_deadline')" type="date"
                     :value="$data['deadline'] ?? null"
                     :autofocus="$errors->has('deadline')"
                     :min="now()->toDateString()"
                     :help="__('messages.rfq_wizard.response_deadline_help')" />
    </div>

    {{-- Reference codes are generated by the platform on submit, so there is no
         field for one here — the buyer receives it on the confirmation screen. --}}
    <p class="rounded-xl bg-sand-100 px-4 py-3 text-[1.0625rem] text-ink-soft dark:bg-[#26241e] dark:text-[#b3ab9b]">
        <x-heroicon-m-information-circle class="mr-1 inline h-4 w-4 align-text-bottom" />
        {{ __('messages.rfq_wizard.reference_auto_note') }}
    </p>
</fieldset>
